-- ─────────────────────────────────────────────────────────────────────────────
-- NATIONAL DRIVE ELECTRIC MONTH 2026 — the public event list
--
-- 120 events pulled from driveelectricmonth.org/events-list (the "National
-- Drive Electric Month Events" table), 11 Sep – 12 Oct 2026. These are other
-- organisations' events, listed by Plug In America, the Electric Vehicle
-- Association, Sierra Club, EVHybridNoire and Drive Electric USA.
--
-- The source table lists 121. Event 5288 (Poolesville) is deliberately NOT
-- imported: it already exists in site_events as a hand-authored row, with a
-- better title and an uploaded flyer that a scrape cannot reproduce. The delete
-- below skips it for the same reason. Do not "fix" either omission.
--
-- REQUIRES 0018 — every row sets hero_hidden. Run 0018 first or this fails on
-- the missing column, which is the intended outcome: without it these rows
-- become the soonest hero-eligible events and take over the homepage carousel.
--
-- WHY ROWS AND NOT data/events.ts: the curated array requires an imported image
-- per event, and these are time-limited — isActive() (data/events.ts) drops any
-- event that is past and not flagged `ours`, so the whole set disappears from
-- the site by itself after 12 Oct 2026. Rows also mean an editor can fix, hide
-- or delete any one of them from /admin/content without a deploy.
--
-- WHAT EACH ROW CARRIES:
--   register_url        the event's own page on driveelectricmonth.org, so
--                       "Event details" sends people to the organiser, not to
--                       our contact form (the blank-register_url fallback).
--   image               left null on purpose. rowToEvent falls back to the
--                       site's stock EV photo; a wrong flyer is worse than none.
--   featured false      keeps them out of the Featured band.
--   hero_hidden true    keeps them off the homepage carousel. See 0018.
--
-- RE-RUNNABLE. The delete matches only rows this file created, so re-running
-- refreshes the import without touching anything else. A re-run DISCARDS edits
-- an editor has made to these 120 rows — that is the trade for being able to
-- re-import cleanly, and it is why 5288 is excluded rather than trusted to
-- survive.
--
-- Apply by running this in the Supabase SQL editor, after 0018.
-- ─────────────────────────────────────────────────────────────────────────────

delete from public.site_events
where register_url like 'https://driveelectricmonth.org/event?eventid=%'
  -- The hand-authored Poolesville row. Never owned by this import.
  and register_url <> 'https://driveelectricmonth.org/event?eventid=5288';

insert into public.site_events
  (event_date, end_date, title, type, location, region, time, description,
   register_url, register_label, register_cta_label,
   image, featured, hero_hidden, hidden, status)
select
  v.event_date::date,
  -- '' rather than a bare null in the VALUES list below: an untyped null in the
  -- first row would leave Postgres to infer the column type from later rows.
  nullif(v.end_date, '')::date,
  -- " - City, ST" appended at import rather than patched afterwards, so a
  -- re-import keeps the convention. See .claude/skills/event-title. All 120
  -- regions are verified "City, ST" pairs, so this never produces a stray dash.
  -- eventTitleClean strips the suffix before rendering a card, so this changes
  -- the /admin/content list and nothing a visitor sees.
  v.title || ' - ' || v.region,
  v.type, v.location, v.region, v.time, v.description,
  'https://driveelectricmonth.org/event?eventid=' || v.eid,
  'Event details', 'View event details',
  null, false, true, false, 'published'
from (values
  ('2026-09-11', '', 'Tailgate & Car Show at NCSU v Richmond Football Game', 'EV Showcase', 'Front of Close King Indoor Practice Facility, 4550 Trinity Rd, Raleigh, NC 27607', 'Raleigh, NC', '3:00 - 7:30 pm EDT', 'NC Clean Energy Technology Center celebrates National Drive Electric Month at NC State University in Raleigh with a tailgate and plug-in electric vehicle car show at the NCSU vs Richmond football game. Due to game-day congestion, we recommend attending only if you have tickets for the game or parking arrangements. Lunch or dinner and soft drinks are provided for volunteers.', '5319'),
  ('2026-09-11', '', 'Electric Transportation Fair', 'Festival', 'Palouse Nature Center, 1040 Rodeo Dr., Moscow, ID 83843', 'Moscow, ID', '4:30 - 7:30 pm PDT', 'The public is welcome to join us to learn about electric cars, trucks, motorcycles, bicycles, and scooters. There will be a variety of electric vehicles to check out, ask questions of the owners, and even test drive. There will be plenty of EV information and community resources.', '5352'),
  ('2026-09-12', '', 'Clinton Township Community Day', 'EV Showcase', 'Bundt Park, 10 Red School House Rd, Lebanon, NJ 08833', 'Lebanon, NJ', '12:00 - 4:00 pm EDT', 'Join the Clinton Township Community Day. We''ll be having an EV Show, EV Test Drives, and more.', '5309'),
  ('2026-09-12', '', 'River City EV Expo', 'Expo', 'Dorey Park Farmers Market, 7155 Dorey Park Drive, Henrico, VA 23231', 'Henrico, VA', '9:00 am - 12:00 pm EDT', 'Get behind the wheel of the latest electric vehicles at the River City EV Expo, presented by Drive Electric RVA, the Electric Vehicle Association, Virginia Clean Cities, ION Solar, and Dominion Energy. Four different EVs are planned for test drives and many more on display, including e-bikes and electric scooters. Register for a test drive and sign a waiver via the online form.', '5317'),
  ('2026-09-12', '', '13th Annual Juneau EV Round Up', 'EV Showcase', 'Juneau District Heating Lot, 300 Egan Drive, Juneau, AK 99801', 'Juneau, AK', '11:00 am - 1:00 pm AKDT', 'Showcasing the full spectrum of EVs driving Juneau''s road system. Burgers, drinks, and a showcase of EV information provided by the Juneau Electric Vehicle Association and local EV dealers. Come share your EV and EV stories. Family fun event, sponsored by IBEW 1547, Juneau Hydropower and local electric vehicle, electric bike and electric outboard dealers.', '5334'),
  ('2026-09-12', '', 'Old Bill''s Fun Run', 'EV Showcase', 'Jackson Elementary School, 200 N Willow St, Jackson, WY 83001', 'Jackson, WY', '9:00 am - 1:00 pm MDT', 'Join Yellowstone-Teton Clean Cities in celebrating National Drive Electric Month at Old Bill''s Fun Run. Stop by our booth to meet EV drivers in the Jackson Hole community, learn more about the new EV charging infrastructure being built in Jackson, and share your ideas for an EV-friendly community.', '5336'),
  ('2026-09-12', '', '2026 Dallas-Fort Worth National Drive Electric Month', 'EV Showcase', 'Downtown Denton Square, corner of N Elm and W Oak, 110 W Hickory St, Denton, TX 76201', 'Denton, TX', '9:00 am - 3:00 pm CDT', 'The 2026 Dallas-Fort Worth National Drive Electric Month provides an opportunity for electric vehicle education in a neutral, no-sale environment. The DFW NDEM event returns to Arts & Autos Electric Avenue in Denton, Texas. Come visit Electric Avenue to see various makes and models of EVs, speak with real EV owners about what ownership is like, take a test ride, and join games and prizes.', '5354'),
  ('2026-09-12', '', 'Lowell Drives Electric', 'EV Showcase', 'Heritage Farm Ice Cream, 163 Pawtucket Boulevard, Lowell, MA 01854', 'Lowell, MA', '12:00 - 4:00 pm EDT', 'EVs are faster, cleaner, and more fun. Lowell Drives Electric is back again for another electric car show. Join us along the banks of the Merrimack River in Lowell, Mass. at Heritage Farm Ice Cream with over 20 electric vehicles and owners. Come learn about EVs, take a ride in one, and get all your questions about EVs answered.', '5358'),
  ('2026-09-12', '', 'Charge and Chat with PNM: Why More New Mexicans Are Driving Electric', 'Meetup', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '12:00 - 1:00 pm MDT', 'Curious about electric vehicles? Join PNM''s Transportation Electrification team for an engaging conversation about why more New Mexicans are choosing to drive electric. Learn about the benefits of EV ownership, available rebates and incentives, charging options, and how transportation electrification is growing across our communities.', '5377'),
  ('2026-09-12', '', 'Cars & Coffee', 'EV Showcase', 'Eastern & Richmar, Las Vegas, NV', 'Las Vegas, NV', '7:00 am - 12:00 pm PDT', 'Join us for a special car show celebrating National Drive Electric Month. We''ll be highlighting electric vehicles and sharing resources about clean transportation while connecting with the community. Enjoy coffee, conversation, and a parking lot full of some of the best cars in Las Vegas, from exotics and classics to hot rods, muscle cars and EVs.', '5382'),
  ('2026-09-12', '', 'Cullman Electric Cooperative Annual Meeting', 'Meetup', 'Northbrook Baptist Church, 3691 AL-157, Cullman, AL 35058', 'Cullman, AL', '9:00 - 11:00 am CDT', 'The Birmingham Area Chapter hosts a Drive Electric Alabama event featuring an EV Showcase, held as part of the Cullman Electric Cooperative Annual Meeting. A fantastic opportunity for attendees to explore the latest in electric vehicle technology, join informative presentations and connect with local EV enthusiasts.', '5390'),
  ('2026-09-12', '', 'Woodrock Community EV Car Show', 'EV Showcase', 'Corner of Laurel Leaf Drive and Goldwood Court, Potomac, MD 20854', 'Potomac, MD', '10:00 am - 2:00 pm EDT', 'Meet your neighbours and their electric vehicles. Curious about EVs? Already driving one? Join us for a relaxed neighbourhood EV gathering during National Drive Electric Month. See a variety of electric cars up close and get candid answers about charging at home, taking road trips, maintaining an EV, and living with one every day.', '5399'),
  ('2026-09-12', '', 'Huber Heights Multicultural Heritage Festival', 'Festival', 'Eichelberger Amphitheatre, 8625 Brandt Pike, Huber Heights, OH 45424', 'Huber Heights, OH', '11:00 am - 6:00 pm EDT', 'Members of the Electric Vehicle Association of Ohio (EVAOH) will be at the Huber Heights Multicultural Festival to answer your questions about living with and driving EVs. Our members have dozens of years of cumulative experience and are happy to take you for a short ride, describing the benefits of going electric. Visit us at our booth.', '5403'),
  ('2026-09-13', '', 'EV Showcase at the Crestone Energy Fair', 'Festival', 'Blue Federal Credit Union, 110 East Silver Avenue, Crestone, CO 81131', 'Crestone, CO', '10:00 am - 2:00 pm MDT', 'EVs in the SLV (San Luis Valley) is joining up with the Crestone Energy Fair to celebrate National Drive Electric Month. The cars are displayed by their owners, who have years of EV ownership and have driven many petroleum-free miles. They are all enthusiastic and willing to discuss their experiences and answer your questions. Owners may take interested people for a ride at their discretion.', '5307'),
  ('2026-09-13', '', 'Green Oakwood EV Rides Event', 'Ride & Drive', 'Oakwood High School / Mack Hummon Stadium, 1298 E Schantz Ave, Oakwood, OH 45419', 'Oakwood, OH', '2:00 - 4:00 pm EDT', 'EVA Ohio joins Green Oakwood for this event celebrating National Drive Electric Month. Electric vehicles from EVA members and local car dealerships will be available for EV rides. This is your chance to see what it feels like to ride in a 100% battery-powered electric car.', '5404'),
  ('2026-09-13', '', 'Wells Energy Show', 'EV Showcase', 'Wells Public Library, Rte 1, Wells, ME 04090', 'Wells, ME', '1:00 - 4:00 pm EDT', 'Our EV Show is now an Energy Show. In addition to EV owners and dealers, e-bikes and electric yard equipment, we now have solar and heat pump installers, insulators, energy auditors, efficiency programmes, solar farms and conservation organisations.', '5416'),
  ('2026-09-14', '', 'Electric Vehicles 101', 'Workshop', 'North Shore Public Library, 250 Route 25A, Shoreham, NY 11786', 'Shoreham, NY', '6:30 - 8:00 pm EDT', 'Looking to buy an EV? Come learn the basics about EVs, charging, available incentives and cost of ownership. Plus see a virtual EV showcase where we review the latest affordable models, luxury vehicles and family-friendly 3-row EVs.', '5374'),
  ('2026-09-16', '', 'Sparking Connections: Volts & Vino', 'Meetup', 'Women Who Charge, 2380 S Broadway Suite A, Denver, CO 80210', 'Denver, CO', '5:30 - 7:30 pm MDT', 'Join Women Who Charge for an evening of networking, conversation, and connection with professionals shaping Colorado''s clean transportation and energy future. Meet industry leaders, innovators, and changemakers working across electric mobility, charging infrastructure, utilities, clean energy, and the broader energy transition.', '5349'),
  ('2026-09-17', '', 'GOEVIN Ride & Drive at NIRPC', 'Ride & Drive', 'Northwestern Indiana Regional Planning Commission (NIRPC), 6100 Southport Rd., Portage, IN 46368', 'Portage, IN', '10:30 am - 1:00 pm CDT', 'Ever wanted to test drive an EV? Join Drive Clean Indiana and GOEVIN at NIRPC to test drive an array of electric vehicle models from local EV drivers and dealerships. Whether you''re curious, cautious, or ready to switch, this is your chance to explore the electric lifestyle. Free to attend. Get your questions answered by experts and discover charging solutions and incentives.', '5357'),
  ('2026-09-17', '', 'Build an EV with PNM', 'Workshop', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '11:00 am - 12:00 pm MDT', 'Get ready to think like an engineer and build like an inventor. In this hands-on workshop, participants construct their own battery-powered electric vehicle while exploring the science behind electric transportation. Using a battery, motor, gears, wheels, and axles, young builders create a working electric circuit and bring a motor to life.', '5385'),
  ('2026-09-18', '', 'Caldwell National Drive Electric Event', 'EV Showcase', 'Indian Creek Plaza, Caldwell, ID', 'Caldwell, ID', '6:00 - 9:00 pm MDT', 'This year''s Drive Electric will be in Caldwell, Idaho, directly adjacent to the Indian Creek Plaza, where they are featuring live music, a food truck, and one other community event. The car show is granted the parking area at S 7th Avenue and Arthur.', '5265'),
  ('2026-09-18', '', 'Tailgate & Car Show at Wake Forest University v Miami Football Game', 'EV Showcase', 'West corner of Allegacy Federal Credit Union Stadium at Piccolo Lane, Winston-Salem, NC 27105', 'Winston-Salem, NC', '3:00 - 7:30 pm EDT', 'NC Clean Energy Technology Center highlights electric transportation at Wake Forest University in Winston-Salem with a tailgate and plug-in electric vehicle car show at the WFU vs Miami football game. Due to game-day congestion, we recommend attending only if you have tickets for the game or parking arrangements. Limited space for EV owner display vehicles.', '5320'),
  ('2026-09-18', '', 'Santa Maria Downtown Friday EV Showcase', 'EV Showcase', '451 S. McClelland St., Santa Maria, CA 93454', 'Santa Maria, CA', '5:30 - 8:30 pm PDT', 'Downtown Fridays in Santa Maria is a family-friendly festival with rows of food vendors, live music from local bands, and lots for kids too. This season brings new and expanded attractions, including an EV Showcase and sustainable transportation education. The showcase presents a variety of electric vehicles, including a public transport bus, commercial applications, dealer offerings, and privately owned EVs with their owners.', '5365'),
  ('2026-09-19', '', 'Volt & Vibe: An Eco-Rider Showcase', 'EV Showcase', 'Salem State University quad by Marsh Hall, Marblehead Rail Trail, 121 Loring Ave., Salem, MA 01970', 'Salem, MA', '1:00 - 4:00 pm EDT', 'Rain date: Saturday 3 October. No cars allowed. Are you considering replacing four wheels with two? Or even a single wheel? Then this is the event for you. Local owners of Personal Electric Vehicles (PEVs), as well as bike shops and dealers, will be on hand to help you learn about getting around this way. Please bring a helmet, and a parent or guardian to sign the waiver if you are under 18.', '5293'),
  ('2026-09-19', '', 'Kearsarge-Sunapee Clean Energy Expo', 'Expo', 'New London Historical Village, 179 Little Sunapee Road, New London, NH 03257', 'New London, NH', '12:00 - 3:00 pm EDT', 'Step into the future of electric mobility and sustainable living. Taste the thrill of electric cars, trucks, vans and e-bikes. Try out our lawn & garden equipment; you may never pump gas again. Power your household with solar panels and home batteries, use heat pumps to heat and cool your living space, and meet local nonprofits promoting sustainability.', '5295'),
  ('2026-09-19', '', 'LOSN Clean Energy and EV Fair', 'Festival', 'Lake Oswego Methodist Church, 1855 South Shore Blvd, Lake Oswego, OR 97034', 'Lake Oswego, OR', '10:00 am - 2:00 pm PDT', 'Join us for Lake Oswego''s 9th Annual Clean Energy and Electric Vehicle Fair, a family-friendly event celebrating our community''s leadership in clean transportation and sustainable living. Learn how to bring clean energy into your home to save money while improving comfort, health and resiliency, and test drive the latest electric models from top dealers. The first 60 test drivers receive a free meal.', '5300'),
  ('2026-09-19', '', 'Monarchs on the Mountain EV Showcase', 'EV Showcase', 'Chandler Park Community Center Grounds, 6500 W 21st St., Tulsa, OK 74127', 'Tulsa, OK', '9:00 am - 1:00 pm CDT', 'Tulsa Area Clean Cities invites you to our annual EV showcase at the 2026 Monarchs on the Mountain festival. Located on the grounds of the Chandler Park Community Center, we will have EVs of various makes and models on display for attendees to visit and test drive at the discretion of their respective owners and participating dealerships.', '5302'),
  ('2026-09-19', '', 'Drive Electric ICT 2026', 'EV Showcase', 'Wichita State University Eugene M. Hughes Metroplex, 5015 E. 29th St. N., Wichita, KS 67220', 'Wichita, KS', '10:00 am - 1:00 pm CDT', 'The City of Wichita is bringing one of their electric buses for us to examine and ask questions about. Our location is new and has plenty of space: we will be on the west side of the building in that parking lot, with access to restrooms inside. Cloud County Community College is coming from Concordia with their Renewable Energy Program trailer.', '5310'),
  ('2026-09-19', '', 'Sustainability Fair & EV Expo', 'Expo', 'Railway Plaza South, 30 Fairmount Ave, Chatham, NJ 07928', 'Chatham, NJ', '10:00 am - 2:00 pm EDT', 'Chatham Borough invites you to their annual Sustainability Fair and EV show at the Chatham Borough Railroad Parking Lot. Many local organisations gather to share community programmes, conservation initiatives, and sustainable ideas. This year the Fair features the Smart Home & Business Zone, an area focused on energy efficiency and water conservation.', '5315'),
  ('2026-09-19', '', 'TCS Drive Electric Month EV Showcase', 'EV Showcase', 'Edelman Fossil Park of Rowan University, 66 Million Mosasaur Way, Sewell, NJ 08080', 'Sewell, NJ', '10:00 am - 2:00 pm EDT', 'Join us at New Jersey''s newest museum, the Edelman Fossil Park of Rowan University, as we celebrate their commitment to sustainability. Hosted by Tri County Sustainability, the New Jersey Electric Vehicle Association, and the South Jersey Electric Vehicle Club, we''ll be showing several models of electric vehicles and telling our stories of making the switch.', '5331'),
  ('2026-09-19', '', 'Drive Electric Kalamazoo', 'EV Showcase', 'Midtown Fresh Market parking lot, 1693 S. Westnedge, Kalamazoo, MI 49008', 'Kalamazoo, MI', '10:00 am - 3:00 pm EDT', 'The big annual Electric Vehicle Show and Tell returns to the Midtown Fresh Market parking lot just south of downtown Kalamazoo. We''ll have a variety of EVs on display along with info and giveaways. Lots of knowledgeable and friendly owners will be on hand to answer all of your questions. No structured schedule: come and go as you like. Test drives may be available.', '5341'),
  ('2026-09-19', '', 'Enfield EV Showcase', 'EV Showcase', 'Market Plus IGA parking lot, 707 S McDaniel Street, Enfield, NC 27823', 'Enfield, NC', '10:00 am - 4:00 pm EDT', 'Sit in the future, right here in Enfield. Enfield Energy Futures is turning a parking lot in the middle of town into something Enfield has never had: a free showcase of electric cars, trucks, and bikes that you can walk right up to, sit inside, and see for yourself. This is not a dealership and there is nothing to buy. It is a community day.', '5350'),
  ('2026-09-19', '', 'Clean Energy Fair and EV Event', 'Festival', 'Keene Parks and Recreation Center, 312 Washington Street, Keene, NH 03431', 'Keene, NH', '10:00 am - 2:00 pm EDT', 'Come and learn about ways to save energy in your home, along with saving fuel by learning about battery electric vehicles. If you are on the fence about driving electric, come and hear from folks who have been driving electric for years. You can learn how to refuel not only at home but on the road.', '5351'),
  ('2026-09-19', '', 'Electric Car Show', 'EV Showcase', 'Carbondale First Christian Church, 306 W. Monroe St, Carbondale, IL 62901', 'Carbondale, IL', '3:00 - 5:00 pm CDT', 'Welcome to the Carbondale EV Car Show. Join us for our annual National Drive Electric Month celebration, hosted by the First Christian Church of Carbondale and co-organised with the Southern Illinois Electric Vehicle Association. Explore an impressive lineup of everyday electric vehicles. The church car park is conveniently located directly west of City Hall.', '5359'),
  ('2026-09-19', '', 'Drive Electric Columbia', 'EV Showcase', 'Soda City Market, Main St, Columbia, SC 29201', 'Columbia, SC', '9:00 am - 1:00 pm EDT', 'Drive Electric Columbia is a free community event held during the Soda City Market in downtown Columbia, connecting residents with electric vehicles through hands-on experiences, real conversations with EV owners, and opportunities to explore the latest electric transportation technology. Attendees can learn about charging, ownership costs, incentives, and everyday EV driving.', '5366'),
  ('2026-09-19', '', 'Drive Electric Month at West Windsor Community Day 2026', 'EV Showcase', 'Duck Pond Park, 560 Meadow Road, Princeton, NJ 08540', 'Princeton, NJ', '12:00 - 4:00 pm EDT', 'Come join over 2,500 attendees for a fun-filled day as part of West Windsor Community Day. With something for the entire family, from music to food vendors to activities for the young ones, add in electric vehicles and a chance to speak directly with owners to hear their real-world experiences with driving an EV.', '5367'),
  ('2026-09-19', '', 'Historic Route 66 Centennial Flagstaff EV Ride & Drive', 'Ride & Drive', 'Flagstaff Parking Lot, 15 N Beaver St, Flagstaff, AZ 86001', 'Flagstaff, AZ', '10:00 am - 2:00 pm MST', 'Join DRIVE Electric Arizona and the City of Flagstaff for a free, hands-on electric vehicle experience in historic downtown Flagstaff. Free to attend. Test drive requirements: drivers must provide a valid driver''s licence and complete a digital liability waiver before driving. As Historic Route 66 celebrates its 100th anniversary, this special event marks the occasion.', '5371'),
  ('2026-09-19', '', 'Drive Electric Alabama EV Showcase', 'EV Showcase', 'Greer''s Market, 260 St. Louis St., Mobile, AL 36602', 'Mobile, AL', '10:00 am - 2:00 pm CDT', 'The Bay Area chapter of Drive Electric Alabama presents the 2026 NDEM EV showcase of privately owned, regularly driven EVs and their owners. Come get your real EV answers about real EV driving from real EV owners.', '5372'),
  ('2026-09-19', '', 'PoutineFest EVA Maine', 'Festival', 'Thompson''s Point, 207 Thompsons Point, Portland, ME 04102', 'Portland, ME', '11:30 am - 4:00 pm EDT', 'The 2026 EVA Maine National Drive Electric Month provides an opportunity for electric vehicle education in a neutral, no-sale environment. This year''s event is held at PoutineFest 2026 in Portland, Maine. Come visit Electric Avenue to see various makes and models of EVs, speak with real EV owners, and take a test ride. Music and a wide variety of food are part of the event.', '5376'),
  ('2026-09-19', '', 'Lancaster Drive Electric Month 2026', 'Festival', 'Downtown Lancaster, West Main Street, Lancaster, NY 14086', 'Lancaster, NY', '10:00 am - 3:00 pm EDT', 'Celebrate the beauty of autumn at the Village of Lancaster''s annual Fall Festival. Explore a vibrant marketplace featuring local artisans, crafters, vendors, community organisations, and unique handmade goods. Enjoy food, seasonal treats, live entertainment and children''s activities. The event also features a Sustainability Expo showcasing local organisations and electric vehicles.', '5378'),
  ('2026-09-19', '', 'Rickwood Caverns State Park Annual Car Show', 'EV Showcase', 'Rickwood Caverns State Park, 3700 Rickwood Park Rd, Warrior, AL 35180', 'Warrior, AL', '9:00 am - 1:00 pm CDT', 'Join us for the Drive Electric Alabama Birmingham Area Chapter EV Showcase at the Rickwood Caverns State Park Annual Car Show. This showcase is a fantastic opportunity for attendees to engage with electric vehicle owners and gain valuable insights into real-world charging experiences, vehicle performance, and the joys of EV ownership.', '5391'),
  ('2026-09-19', '', 'SOKO Place Festival', 'Festival', 'Covenant United Methodist Church, 529 W. Johnny Lytle Ave, Springfield, OH 45506', 'Springfield, OH', '10:00 am - 6:00 pm EDT', 'EVAOH will offer EV rides in a variety of electric vehicles to passengers 18+, with a signed waiver. EV owners will share their electric cars with community members interested in experiencing an electric car ride. Diverse food options, live music performances, and community speakers will be on hand for all to enjoy.', '5407'),
  ('2026-09-19', '', 'Drive Electric Barry County', 'EV Showcase', 'Historic Charlton Park, 2545 South Charlton Park, Hastings, MI 49058', 'Hastings, MI', '10:00 am - 2:00 pm EDT', 'An electric vehicle Show and Tell will be held at Historic Charlton Park as part of the Barry County Outdoor Youth Day. Knowledgeable, friendly owners will be present to address questions, and printed information and give-aways are available. Outdoor Youth Day gives families hands-on experience in outdoor activities; over 300 youth attended in 2025.', '5413'),
  ('2026-09-19', '2026-09-20', 'E-Volution Expo', 'Expo', 'Roland E. Powell Convention Center, 4001 Coastal Hwy, Ocean City, MD 21842', 'Ocean City, MD', 'Varies by day — see event details', 'E-Volution Expo returns to Ocean City, Maryland for a two-day celebration of electric vehicles, technology, sustainability, innovation, health and wellness, and future-focused solutions. Hosted at the Roland E. Powell Convention Center, the expo brings emerging technologies and practical innovations together in one place, giving attendees an opportunity to discover what''s changing the way we drive, live and work.', '5414'),
  ('2026-09-19', '', 'Fall Festival at Leopold''s Preserve', 'Festival', '16290 Thoroughfare Rd, Broad Run, VA 20137', 'Broad Run, VA', '10:00 am - 2:00 pm EDT', 'The festival brings together partners in conservation from the region to celebrate our efforts and educate the community on what we do. Come out to enjoy the preserve and learn about its conservation. Talk to volunteers about their experiences owning an electric vehicle. This is a no-pressure way to learn the reality of EV ownership. Space for EVs is limited.', '5415'),
  ('2026-09-19', '', 'Milwaukie Sustainability Fair', 'Festival', 'Farmers Market Parking Lot, 10723 SE Main St., Milwaukie, OR 97222', 'Milwaukie, OR', '10:00 am - 3:00 pm PDT', 'Experience sustainable living, on the road and at home. See what it''s like to drive electric at PGE''s free EV Ride & Drive during the Milwaukie Sustainability Fair. Test drive a variety of EVs, connect with EV experts, and learn about charging, incentives, and EV ownership. Afterwards, discover local organisations, educational exhibits, live music and food vendors.', '5423'),
  ('2026-09-20', '', 'Get Charged Up Regional EV Expo', 'Expo', '50 Otis Street, Westborough, MA 01581', 'Westborough, MA', '2:00 - 5:00 pm EDT', 'The Get Charged Up Regional EV Expo is the perfect opportunity to learn more in a no-pressure, free community event. We expect a large variety of vehicles: last year we had over 25 different models including multiple Tesla models, Chevy Bolt, Nissan Leaf, Toyota RAV4 Prime, VW ID.4 and ID.Buzz, Ford Mustang Mach-E, Kia Niro, Rivian R1T and R1S, BMW i5, Hyundai Ioniq 5 and 9, and Chevy Equinox.', '5294'),
  ('2026-09-20', '', 'Charge and Chat with PNM: Everything You Need to Know About EV Charging', 'Meetup', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '12:00 - 1:00 pm MDT', 'Thinking about driving electric but unsure about charging? Join PNM''s Transportation Electrification team for an informative discussion that takes the mystery out of EV charging. Learn the differences between home, workplace, and public charging, how long charging typically takes, what equipment you may need, and how charging fits into your daily routine.', '5380'),
  ('2026-09-20', '', 'EV Showcase at Mid-City Farmers Market', 'EV Showcase', 'Mid-City Farmers Market, 5909 University Dr, Huntsville, AL 35806', 'Huntsville, AL', '12:00 - 4:00 pm CDT', 'The North Alabama Chapter of Drive Electric Alabama hosts an EV Showcase at the Mid-City Farmers Market. Participants have the opportunity to explore a variety of electric vehicles and engage with knowledgeable representatives from the EV industry.', '5394'),
  ('2026-09-21', '', 'Let''s Taco ''Bout EVs!', 'EV Showcase', 'GBHS Memorial Stadium, 2027 Morton St., Great Bend, KS 67530', 'Great Bend, KS', '4:30 - 6:30 pm CDT', 'Great Bend, let''s taco ''bout EVs. We''re celebrating National Drive Electric Month with free tacos, Monday night football, and a chance to get up close with Wheatland Electric''s all-electric vehicles. Check out our Hyundai Kona Electric and Ford F-150 Lightning, and get answers to those EV questions you''ve always wondered about. No sales pitch, no pressure.', '5417'),
  ('2026-09-22', '', 'Ride Your Range ChargeWest Scenic Byway', 'Ride & Drive', 'Springdale, 118 Lion Blvd, Springdale, UT 84767', 'Springdale, UT', '7:00 am - 3:00 pm MDT', 'Celebrate National Scenic Byway Day and National Drive Electric Month with Utah Clean Cities and Communities, ChargeWest, and partners across the eight-state Intermountain West. Through ChargeWest''s Ride Your Range campaign, EV drivers, families, outdoor enthusiasts, community leaders and local businesses are invited to join coordinated EV touring events along some of the West''s most memorable scenic byways.', '5347'),
  ('2026-09-23', '', 'Webinar: Electric Vehicle Benefits & How to Make the Switch', 'Webinar', 'Online — hosted from Las Vegas, NV', 'Las Vegas, NV', '1:00 - 1:30 pm PDT', 'Presented by the Nevada Electric Vehicle Association. Discover the environmental and financial benefits of driving electric and learn what to expect when transitioning to an EV. This session covers cost savings, charging options, incentives, and practical tips to help you make a smooth and confident switch. Please register to receive the livestream link.', '5342'),
  ('2026-09-23', '', 'Electric Vehicles Are Cool', 'EV Showcase', 'Gateway Technical College, 1001 South Main Street, Racine, WI 53403', 'Racine, WI', '2:00 - 5:00 pm CDT', 'We will have a good variety of great looking electric vehicles from actual drivers to answer all your questions. We hope to have information about used EVs as well as the latest new EVs. Adding to that, we will provide information on how to power your EV with solar, or Level 2 chargers, or public charging stations.', '5345'),
  ('2026-09-24', '', 'Build an EV with PNM', 'Workshop', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '11:00 am - 12:00 pm MDT', 'Get ready to think like an engineer and build like an inventor. In this hands-on workshop, participants construct their own battery-powered electric vehicle while exploring the science behind electric transportation. Using a battery, motor, gears, wheels, and axles, young builders create a working electric circuit and bring a motor to life.', '5387'),
  ('2026-09-26', '', 'National Drive Electric Month Showcase', 'EV Showcase', 'Well Crafted Beer Garden / Ambler Yards, 300 Brookside Ave upper parking lot, Ambler, PA 19002', 'Ambler, PA', '12:00 - 5:00 pm EDT', 'Join us for the 2026 National Drive Electric Month event in Ambler, Pennsylvania, a free, family-friendly celebration of all-electric vehicles and clean energy. This hands-on community showcase brings together EV owners, curious drivers, and clean-energy enthusiasts to explore the latest all-electric vehicles, plus power demonstrations for power tools and vehicle-to-home. Sit inside and ask questions.', '5135'),
  ('2026-09-26', '', 'EV Showcase at the Port of Hueneme Banana Festival', 'Festival', 'The Port of Hueneme, 105 East Port Hueneme Road, Port Hueneme, CA 93041', 'Port Hueneme, CA', '10:00 am - 5:00 pm PDT', 'Join thousands from our community in celebrating the 13th annual Banana Festival at The Port of Hueneme, a truly diverse working port. This festival features many attractions, including port tours, a Kids Zone, live bands, tasty eats and shopping. An EV Showcase and educational booth will be provided by the Electric Vehicle Advocates of Ventura County.', '5275'),
  ('2026-09-26', '', 'Southeast Idaho Electric Car Show', 'EV Showcase', 'Lookout Point Park, 426 W Lewis St, Pocatello, ID 83204', 'Pocatello, ID', '9:00 am - 1:00 pm MDT', 'Portneuf Resource Council holds our annual Southeast Idaho Electric Car Show in Pocatello in conjunction with National Drive Electric Month. The show runs at the same time as the Portneuf Valley Farmers Market at Lookout Point. Seasoned local EV owners will be showing their electric and plug-in hybrid vehicles and can answer questions about range, cost, maintenance and charging.', '5291'),
  ('2026-09-26', '', 'Electric Ave - Sustainability Fair & EV Car Show', 'Festival', 'Park Avenue and Central Park, 111 N Park Ave, Winter Park, FL 32789', 'Winter Park, FL', '9:00 - 11:00 am EDT', 'The City of Winter Park''s Natural Resources & Sustainability Department invites you to Electric Ave, our 5th Annual Sustainability Fair & EV Car Show. This family-friendly event brings the community together to celebrate clean transportation and sustainable living. Explore 30+ electric vehicles, including cars and buses, displayed along Park Avenue in downtown Winter Park.', '5296'),
  ('2026-09-26', '', 'Iowa City Climate Fest EVs at the Market', 'EV Showcase', 'Iowa City Farmers Market, east side of City Hall, 410 E Washington St, Iowa City, IA 52240', 'Iowa City, IA', '7:30 am - 12:00 pm CDT', 'Driving an electric vehicle is convenient, less expensive than driving a gas car, and fun. Whether you already own an EV and want to share the love, or you are EV-curious and want a chance to talk to real, local drivers, this event is for you. There will also be information on Iowa City resources for EVs, including the locations of local charging stations.', '5301'),
  ('2026-09-26', '', 'He Ala Pono EV and Sustainability Fair 2026', 'Festival', 'Prince Kuhio Plaza, 111 E. Puainako St., Hilo, HI 96720', 'Hilo, HI', '10:00 am - 2:00 pm HST', 'Hawaii EV Association, Hawaiian Electric, and Sustainable Energy Hawaii host the 2026 He Ala Pono Electric Vehicle and Sustainability Fair, celebrating National Drive Electric Month and sustainability on Hawaii Island. The event features indoor and outdoor activities highlighting clean transportation, clean energy, food security, environmental protection and community resilience.', '5303'),
  ('2026-09-26', '', 'Drive Electric, Save Money at StoreLocal Napa', 'EV Showcase', 'StoreLocal Napa, 1111 Soscol Ferry Road, Napa, CA 94558', 'Napa, CA', '1:00 - 4:00 pm PDT', 'StoreLocal Napa recently installed 30 Autel 10.4 kW AC chargers and a 300 kW Kempower distributed charging system split between six ports, for EV fleet owners and operators, rideshare drivers, commuters, carpoolers, local agencies, and the public. Current models of electric vehicles will be on display. Learn from EV drivers and enthusiasts about how they charge and save.', '5304'),
  ('2026-09-26', '', 'Salem Electric Cars & Coffee', 'EV Showcase', 'Salem Electric, 633 7th St NW, Salem, OR 97304', 'Salem, OR', '9:00 - 11:00 am PDT', 'Join us for a fun and energising morning of coffee, conversation, and electric vehicles. Whether you already drive an EV or you''re just curious, this is your chance to connect with fellow enthusiasts, show off your ride, and check out the latest electric models from local dealerships. Bring your EV, or just bring your curiosity.', '5306'),
  ('2026-09-26', '', 'Rochester Eco Fair and EV Show 2026', 'Festival', 'Henrietta Town Hall, 475 Calkins Rd, Rochester, NY 14623', 'Rochester, NY', '10:00 am - 1:00 pm EDT', 'Local electric vehicles (BEVs and PHEVs) will be at the event and their owners will share what it''s like to drive an EV and answer any related questions. This is our 15th year running the Rochester Area National Drive Electric Week (now Month) fall event. A number of companies and not-for-profit exhibitors will be present.', '5308'),
  ('2026-09-26', '', 'Electrify Lewiston 2026', 'Expo', '402 Center Street, Lewiston, NY 14092', 'Lewiston, NY', '10:00 am - 4:00 pm EDT', 'Electrify Lewiston 2026, the 5th Annual EV and Clean Energy expo, is a showcase for EV drivers from the Electric Vehicle Association of WNY and other local EV drivers. Attendees can meet our EV drivers (full battery electric, hybrid and plug-in hybrid vehicles) and their vehicles, and spend time learning what it is like to own and drive an EV. We''ll have data on how our EV drivers use their cars day to day, and their road trips.', '5330'),
  ('2026-09-26', '', 'Midstate''s EV Showcase at the Anything with Wheels Car Show', 'EV Showcase', 'La Pine Parks & Recreation Community Center, 16405 1st Street, La Pine, OR 97739', 'La Pine, OR', '9:00 am - 4:00 pm PDT', 'Join us for Midstate''s EV Showcase at the Anything on Wheels Car Show in La Pine. If you own an electric vehicle, we''d love for you to bring it and display it in our EV Showcase; EV owners are encouraged to RSVP and let us know what type of vehicle they''ll be bringing. This free, family-friendly event is open to everyone. Learn about Midstate''s public EV charging stations.', '5335'),
  ('2026-09-26', '', 'EV in DC 2026', 'EV Showcase', '14th St and Madison Dr NW, Washington, DC 20004', 'Washington, DC', '10:00 am - 3:00 pm EDT', 'Ready to break free from the gas pump? Come explore today''s electric vehicles. Talk with local EV owners from the Electric Vehicle Association of Greater Washington DC. They''ll share honest, first-hand experiences and answer your questions — no salespeople, just real owners. Compare multiple plug-in vehicles in one location, including Chevrolet, Kia, Ford, Tesla, Polestar and more.', '5343'),
  ('2026-09-26', '', 'Kensington Heights EV Expo', 'Expo', 'Kenmont Swim & Tennis Club, 2900 Faulkner Place, Kensington, MD 20895', 'Kensington, MD', '9:00 am - 1:00 pm EDT', 'Rain date: Sunday 27 September. Talk to local EV owners and see cars up close, go for a ride in an EV, and get real answers to your questions, from charging to road trips. No pressure, no sales pitch. Already have an EV? Bring it and show it off. A community yard sale runs alongside, with an ice cream truck on site.', '5344'),
  ('2026-09-26', '', 'Reid Hillview Airport Day', 'Festival', 'Reid Hillview Airport, 2500 Cunningham Avenue, San Jose, CA 95148', 'San Jose, CA', '10:00 am - 4:00 pm PDT', 'National Drive Electric Month event at Reid Hillview Airport, presented by Plug In America, the Electric Vehicle Association, Sierra Club, EVHybridNoire and Drive Electric USA. Free parking and free tickets online. Electric cars, Archer Aviation, a robot zoo, Culture Camp, Civil Air Patrol, drones, an RC air show, education exhibits, career information and a rocket launch.', '5348'),
  ('2026-09-26', '', 'Recharge Northfield EV Ride & Drive', 'Ride & Drive', 'Northfield Middle School, 2200 Division Street South, Northfield, MN 55057', 'Northfield, MN', '11:00 am - 3:00 pm CDT', 'Join us at Northfield Middle School for a fun and engaging experience: local vendors and organisations, food trucks offering coffee, drinks, lunch and sweet treats, family-friendly activities, and hands-on learning experiences for all ages. Plus an EV ride-and-drive bringing EV education and public test drives to you — and for a good cause.', '5363'),
  ('2026-09-26', '', 'Eugene Bright Parade and After Party', 'Festival', 'Lane County Farmers Market Pavilion, 85 E 8th Ave, Eugene, OR 97401', 'Eugene, OR', '6:00 - 10:00 pm PDT', 'We begin with the Eugene Bright Parade and line up an hour before the event with other entries. EV drivers, bring your car and festive lights — we will have some lights to lend for the parade. Stay to help with the booth at the after-party. Register yourself and your EV for the parade, or just come to help out at the after-party.', '5369'),
  ('2026-09-26', '', 'Take Charge East LA Ride and Drive', 'Ride & Drive', 'Lincoln Park, 3501 Valley Blvd, Los Angeles, CA 90031', 'Los Angeles, CA', '10:00 am - 1:00 pm PDT', 'Join us for the Take Charge East LA Ride and Drive and experience the future of driving first-hand. Whether you are just curious about electric vehicles or ready to make the switch, this is your opportunity to get behind the wheel of an EV and see what all the excitement is about. Free family event with test drives available.', '5405'),
  ('2026-09-27', '', 'Sustainability Action EV Show — Bikes, Buses, Cars, Trucks', 'EV Showcase', 'South Park concourse (closed to traffic), 1141 Massachusetts St., Lawrence, KS 66044', 'Lawrence, KS', '11:00 am - 3:00 pm CDT', 'Lawrence''s largest electric vehicle show, covering e-bikes, buses, cars and trucks. Sponsorship is open to organisations that want to demonstrate their commitment to clean transportation, with four tiers, each including a booth at the show.', '5279'),
  ('2026-09-27', '', 'EVs@thePavilion & Transportation Fair 2026', 'Festival', 'Davis Central Park Pavilion, 301 C Street, Davis, CA 95616', 'Davis, CA', '11:00 am - 2:30 pm PDT', 'Thinking about buying an electric vehicle, or simply curious about what it''s like to own one? EVs@thePavilion & Transportation Fair returns to downtown Davis, offering a free opportunity to explore electric vehicles and other sustainable transport options while talking with local EV owners. Visitors can compare electric vehicles and ask questions about charging and ownership.', '5364'),
  ('2026-09-27', '', 'National Drive Electric Month EV Summit', 'Conference', 'The Arroyo Market, 7285 Arroyo Crossing Pkwy, Las Vegas, NV 89118', 'Las Vegas, NV', '11:00 am - 3:00 pm PDT', 'Join the Nevada EVA for an event celebrating National Drive Electric Month. Our plan is to have dealers available for ride and drive, as well as many EVs on display. We will also offer the opportunity to speak with EV owners and get your questions answered by people who have been driving electric and can help identify pain points and ways to overcome them.', '5383'),
  ('2026-09-27', '', 'Charge and Chat with PNM: Your Roadmap to Driving Electric', 'Meetup', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '12:00 - 1:45 pm MDT', 'Thinking about making the switch to an electric vehicle? Join PNM''s Transportation Electrification team for a practical conversation about what it takes to go electric. Learn about EV ownership, charging options, available rebates and incentives, potential savings, and how electric transportation is growing across New Mexico.', '5386'),
  ('2026-09-27', '', 'EV Showcase at the Long Island Family Festival', 'Festival', 'Tanner Park, 400 Baylawn Avenue, Copiague, NY 11726', 'Copiague, NY', '12:00 - 4:00 pm EDT', 'Curious about electric vehicles? Come see a variety of EVs at the Drive Electric Long Island EV Showcase at Tanner Park in Copiague, held as part of the Long Island Family Festival. Talk to EV owners about what it''s really like to drive an EV.', '5412'),
  ('2026-09-28', '', 'EV First Responder Workshop at Pompton Lakes Fire Department', 'Workshop', 'Pompton Lakes Fire Department, 1 Passaic Ave, Pompton Lakes, NJ 07442', 'Pompton Lakes, NJ', '7:30 - 9:15 pm EDT', 'New Jersey EVA offers an EV awareness workshop for first responders in New Jersey. Particularly suitable for firefighters, it aims to increase awareness of EV-specific safety procedures for responders deployed to a scene involving electric vehicle collisions. The programme is one hour of in-class presentation followed by an hour of hands-on inspection of plug-in vehicles using First Responder Guides.', '5379'),
  ('2026-09-29', '', 'Fleet Forward Electric Ride & Drive', 'Ride & Drive', 'Portland International Raceway, 1940 N Victory Blvd, Portland, OR 97217', 'Portland, OR', '10:00 am - 3:00 pm PDT', 'Designed for fleet managers, operators, maintenance professionals, and organisations exploring fleet electrification, this hands-on event offers the opportunity to test drive zero-emission medium- and heavy-duty vehicles, explore the latest fleet and charging technologies, and connect with industry experts. Hosted by the Oregon Department of Transportation and the Oregon Department of Energy.', '5420'),
  ('2026-09-30', '', 'EV Basics', 'Workshop', 'GS Motors, 10921 Excelsior Blvd #114, Hopkins, MN 55343', 'Hopkins, MN', '5:30 - 7:30 pm CDT', 'Thinking of buying an electric vehicle? Own an EV and have questions about how to use it? This workshop covers what to consider when purchasing an EV, how to charge for daily use, how to use DC fast chargers, and how to plan for road trips. Afterwards you''ll have an opportunity to see a variety of used EVs. Your instructor, Stu Henry, has been an EV owner since 2017.', '5406'),
  ('2026-10-01', '', '29th Annual Haunted Happenings Parade', 'Festival', 'Shetland Park (starting point), 27 Congress St., Salem, MA 01970', 'Salem, MA', '5:30 - 8:30 pm EDT', 'For the EV-curious: come see the parade and check out EVs at this fun annual event. No need to register, but we recommend arriving in Salem early due to road closures and lack of parking. EV owners: this is not your typical EV showcase and not a ride-and-drive, so there will be limited time to interact with parade-goers. The intent is an EV segment as a counterpoint to the several Jeep segments.', '5297'),
  ('2026-10-01', '', '2026 EV Ride & Drive at Beltrami Electric Cooperative', 'Ride & Drive', 'Beltrami Electric Cooperative (in the garage), 4111 Technology Dr NW, Bemidji, MN 56601', 'Bemidji, MN', '4:00 - 6:00 pm CDT', 'Join us at Beltrami Electric for this year''s EV car show. Guests will have the chance to visit with EV owners and get up close with a variety of EVs. Representatives from Beltrami Electric Cooperative and Otter Tail Power Co. will be on hand to share how you can save with off-peak rates and rebates on EV charging. Ride and drive: Ford F-150 Lightning, Chevy Silverado EV, Tesla Model 3 and Polaris Ranger Kinetic.', '5299'),
  ('2026-10-01', '', 'Build an EV with PNM', 'Workshop', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '11:00 am - 12:00 pm MDT', 'Get ready to think like an engineer and build like an inventor. In this hands-on workshop, participants construct their own battery-powered electric vehicle while exploring the science behind electric transportation. Using a battery, motor, gears, wheels, and axles, young builders create a working electric circuit and bring a motor to life.', '5388'),
  ('2026-10-01', '', 'NHEC EV Cruise Night 2026', 'EV Showcase', 'Route 104 Diner, 752 NH-104, New Hampton, NH 03256', 'New Hampton, NH', '4:00 - 6:30 pm EDT', 'Come and learn about electric vehicles (EVs) and plug-in hybrid electric vehicles (PHEVs). Owners, please bring your EVs and PHEVs to show, and share your knowledge and experience with those wanting to learn about these vehicles. NHEC will be there to talk about their experience, knowledge and programmes. This is always a fun, well-attended event.', '5419'),
  ('2026-10-02', '', 'Odyssey Day and National Drive Electric Month', 'Expo', 'CCAC West Hills Center, 1000 McKee Road, Oakdale, PA 15071', 'Oakdale, PA', '8:30 am - 2:30 pm EDT', 'Join Pittsburgh Region Clean Cities (PRCC) and the Three Rivers Electric Vehicles Association (TREVA) for a National Drive Electric Month EV Showcase at Odyssey Day 2026. Held annually on the first Friday in October, Odyssey Day is the Pittsburgh region''s largest showcase of alternative and electric fuelled vehicles, with panel presentations, a keynote speaker, a networking luncheon and a large vehicle display.', '5328'),
  ('2026-10-02', '', 'Roanoke Cooperative Clean Energy Expo 2026', 'Expo', 'Ahoskie Creek Amphitheater, 125 Edgewood Dr., Ahoskie, NC 27910', 'Ahoskie, NC', '10:00 am - 2:00 pm EDT', 'Roanoke Cooperative announces the return of our 7th Annual Clean Energy Expo. The expo celebrates cutting-edge clean energy solutions and highlights the concept of beneficial electrification. Each year the event brings together more than 300 students, community members, educators, industry experts and exhibitors to explore the importance and benefits of clean energy.', '5338'),
  ('2026-10-03', '', 'EV Expo in Madison', 'Expo', 'Maple Ave parking lot near Borough Hall, 10 Maple Ave., Madison, NJ 07940', 'Madison, NJ', '10:00 am - 5:00 pm EDT', 'This is the fifth annual EV Expo in Madison, held in conjunction with Bottle Hill Day, a huge fair with hundreds of vendors, family amusements, food and music. Estimates are that Bottle Hill Day draws between 10,000 and 20,000 attendees each year. Last year the Expo featured 13 brands of EVs brought by owners and dealers, several offering test drives.', '5199'),
  ('2026-10-03', '', 'Placer Plug In Day', 'EV Showcase', 'First Congregational Church, 710 Auburn Ravine Drive, Auburn, CA 95603', 'Auburn, CA', '10:00 am - 2:00 pm PDT', 'Placer Plug In Day is a free community event organised by Placer Earth Care Action. Participating sponsors include Placer County, City of Auburn, Auburn Kiwanis Club, Placer Community Energy, PG&E and the Placer Air Pollution Control District. There will be a resource fair, plus speakers on electric cars, electric bikes and home electrification.', '5311'),
  ('2026-10-03', '', 'Lafayette Cars and Coffee Electric Avenue', 'EV Showcase', 'Flatirons Church Parking Lot, 355 W South Boulder Road, Lafayette, CO 80026', 'Lafayette, CO', '6:50 - 10:00 am MDT', 'Come talk to EV owners, or if you have an EV, bring it to our monthly EV show at Lafayette Cars and Coffee. Get there by 6:50 AM to park near our crew. Owners, this is your chance to demonstrate the cutting-edge technology of EVs to car enthusiasts and swap stories with other EV owners. Spot our white "Ask Us About Electric Vehicles" sign. This event takes place the first Saturday of every month.', '5313'),
  ('2026-10-03', '', 'Plug Life Fiesta: PNM''s 5th Annual Electric Car Show on the Plaza', 'EV Showcase', 'Santa Fe Plaza, 63 Lincoln Ave, Santa Fe, NM 87501', 'Santa Fe, NM', '10:00 am - 2:00 pm MDT', 'Experience the excitement of electric transportation at the Plug Life Fiesta, the 5th Annual EV Car Show on the Plaza, hosted by PNM''s Transportation Electrification Program. This signature community event highlights the growing EV movement across New Mexico with a showcase of electric vehicles, clean energy solutions, educational exhibits, and family-friendly activities.', '5322'),
  ('2026-10-03', '', 'energz EV Expo', 'Expo', 'Banning High School, 100 West Westward, Banning, CA 92220', 'Banning, CA', '10:00 am - 2:00 pm PDT', 'Join us at energz EV Expo in Banning, California, for a free, family-friendly National Drive Electric Month celebration with entertainment, education, food, and community connection. Meet experienced EV owners and owners from area car clubs who bring their vehicles to display and talk about their benefits. Experience EVs through guided test drives, and meet EV dealers bringing vehicles for display.', '5329'),
  ('2026-10-03', '', 'TCS Drive Electric Month 2026 EV Showcase', 'EV Showcase', 'Ballard Park, 15 Pitman Ave, Pitman, NJ 08071', 'Pitman, NJ', '11:00 am - 2:00 pm EDT', 'Hosted by Tri County Sustainability, the New Jersey Electric Vehicle Association, and the South Jersey Electric Vehicle Club. Join us as we team up with Sustainable Pitman for the 2nd annual Pitman Green Fair. We''ll be in the parking lot next to Ballard Park in uptown Pitman. As a bonus, Pitman Porchfest is happening on the same day, so there will be live music.', '5333'),
  ('2026-10-03', '', 'Talent Harvest Festival', 'Festival', '300 Main St, Talent, OR 97540', 'Talent, OR', '10:00 am - 4:00 pm PDT', 'SOHEVA members will again be providing information and answering questions about driving on electricity instead of fossil fuels. We will also have solar electric car races for the kids. The harvest festival does not allow vehicles in the booth area.', '5339'),
  ('2026-10-03', '', 'Phoenix EV Ride & Drive', 'Ride & Drive', 'Luke Elementary School, 7300 N Dysart Road, Glendale, AZ 85307', 'Glendale, AZ', '9:00 am - 2:00 pm MST', 'Get behind the wheel, experience electric driving, meet local EV owners, and enjoy two automotive events in one family-friendly day. No sales pressure — just real cars, real owners, and real answers. Presented in partnership with the 56th EMS 2nd Annual Auto Show. Free admission and free EV test drives.', '5355'),
  ('2026-10-03', '', 'Bartlett Festival EV Showcase', 'Festival', 'W. J. Freeman Park, 2629 Bartlett Blvd, Bartlett, TN 38134', 'Bartlett, TN', '9:00 am - 5:00 pm CDT', 'The Bartlett Festival, BBQ Contest & Car Show runs all day at W. J. Freeman Park. Contact the organisers to volunteer in our booth or to show your electric vehicle.', '5362'),
  ('2026-10-03', '', 'Saddlebrooke/Tucson EV Showcase', 'EV Showcase', 'Saddlebrooke Two, 38759 S Mountain View Blvd, Tucson, AZ 85739', 'Tucson, AZ', '7:00 - 11:30 am MST', 'Join DRIVE Electric Arizona and the Tucson Electric Vehicle Association for a free EV Showcase and Ride & Drive event in the Saddlebrooke area. Experience modern electric vehicles with a test ride or drive, meet experienced EV owners, and get honest answers about charging, ownership costs, incentives, road trips, home charging and everyday electric driving.', '5370'),
  ('2026-10-03', '', 'National Solar Tour EV Rally', 'Ride & Drive', 'Lakeland Transit Center, 7601 Clocktower Drive, Kirtland, OH 44094', 'Kirtland, OH', '10:00 am - 12:00 pm EDT', 'This EV rally at the Polivka Transit Center, at the entrance to Lakeland Community College, is part of this year''s National Solar Tour, organised by the American Solar Energy Society with additional sponsorship from Yellowlite Solar Services. EV owners are invited to attend and display their vehicles, and Laketran will exhibit and explain one of the ten all-electric buses in its fleet.', '5375'),
  ('2026-10-03', '', 'NDEM Lihue 2026', 'EV Showcase', 'Kukui Grove Center, 3-2600 Kaumualii Hwy, Lihue, HI 96766', 'Lihue, HI', '11:00 am - 2:00 pm HST', 'Kauai EV and Hawaii EV are proud to host National Drive Electric Month at Kukui Grove Center.', '5384'),
  ('2026-10-03', '', 'Electric Cars & Coffee', 'EV Showcase', 'Yark Chevrolet, 26997 North Dixie Highway, Perrysburg, OH 43551', 'Perrysburg, OH', '9:00 am - 12:00 pm EDT', 'Join us for Cars & Coffee, electrified. Stop by Yark Chevrolet to find out more about EVs and the electric driving lifestyle. There have been so many technological innovations over the years that an EV fits into most people''s lives. Talk with EV drivers and discover why the majority of them would never go back to petrol vehicles. Test drive a Chevy EV and register for a grand prize.', '5396'),
  ('2026-10-03', '', 'National Drive Electric Month Waterloo 2026', 'EV Showcase', 'The Boardwalk Medical Centre 1, north parking lot, 430 The Boardwalk, Waterloo, ON N2T 0C2, Canada', 'Waterloo, ON', '11:00 am - 3:00 pm EDT', 'It''s WREVA''s 12th anniversary of hosting a National Drive Electric Month event in the Waterloo Region. For the last eight years in a row, this event has had the most registrations of electric vehicles and participants in all of Canada.', '5210'),
  ('2026-10-04', '', 'NY Capital District Drive Electric & Sustainability Fair', 'Festival', 'Schenectady City Hall / Greenmarket, 105 Jay Street, Schenectady, NY 12305', 'Schenectady, NY', '10:00 am - 2:00 pm EDT', 'Join us in downtown Schenectady for the 2026 NY Capital District Drive Electric & Sustainability Fair, a nationally recognised celebration of clean transportation, innovation and community action. Held during National Drive Electric Month, this free, family-friendly event continues its legacy as one of the largest Drive Electric events in the United States.', '5248'),
  ('2026-10-04', '', 'Ventura County EV Showcase', 'EV Showcase', 'Main Lawn, Ventura Harbor Village, 1591 Spinnaker Drive, Ventura, CA 93001', 'Ventura, CA', '12:00 - 4:30 pm PDT', 'We return to Ventura Harbor Village with another outstanding event. On the main lawn you will find a showcase of electric vehicles: cars, vans, SUVs, trucks, bikes, and other electric equipment, as well as vintage EV conversions. The cars are displayed by their owners, who have years of EV ownership and have driven many petroleum-free miles.', '5254'),
  ('2026-10-04', '', 'AustinEV Road Rally Scavenger Hunt', 'Ride & Drive', 'Tesla Superchargers in Dripping Springs, 13810 Sawyer Ranch Rd (behind the Circle K), Dripping Springs, TX 78620', 'Dripping Springs, TX', 'Starts 10:00 am CDT', 'Join us for a fun, free road rally, even if you don''t have an electric vehicle. We drive a very scenic, narrow, twisty route from Dripping Springs to Johnson City. Along the way, driver-navigator teams look out their windows to answer scavenger-hunt questions. The route takes us to a restaurant where we can get lunch and review answers. Need a driver or navigator? We will match you onto a team.', '5324'),
  ('2026-10-04', '', 'Electrify Longmont Fair 2026', 'Festival', 'Boulder County Fairgrounds, 9595 Nelson Road, Longmont, CO 80501', 'Longmont, CO', '10:00 am - 2:00 pm MDT', 'Electrify Longmont features an EV showcase from owners and dealers in collaboration with Recharge America, e-bikes and test rides, live performances, food trucks and lots more.', '5337'),
  ('2026-10-04', '', 'Plug-In NCW''s 4th Annual EV Line-Up', 'EV Showcase', 'Pybus Public Market, 3 North Worthen Street, Wenatchee, WA 98801', 'Wenatchee, WA', '7:30 - 10:00 am PDT', 'Plug-In NCW and Wenatchee Cars & Coffee are joining forces to celebrate Drive Electric Month. Gather and visit in the west parking lot from 7:30, meet EV drivers and ask questions about driving electric. All EVs are welcome to park here. Introductions from the stage at 9:15, then the EV line-up and official count at 9:30. The current record for most EVs in a line in North Central Washington is 28.', '5340'),
  ('2026-10-04', '', 'Electric Vehicles'' Showcase of Eastern Nebraska', 'EV Showcase', 'First United Methodist Church, 7020 Cass St., Omaha, NE 68132', 'Omaha, NE', '12:00 - 3:00 pm CDT', 'Come attend the Nebraska Sierra Club and Eastern Nebraska Electric Vehicle Association''s 6th Annual Omaha Area show. The Eco Team at First United Methodist Church is hosting this year''s event at its spacious facility. The vehicle display is in the parking lot on the east side of the church, and visitor parking is on the north side. Come meet the many enthusiastic EV owners displaying their vehicles.', '5356'),
  ('2026-10-07', '', 'Real Women. Real EVs. An EV Community Night', 'Meetup', 'Lady Justice Brewery, 3242 S Acoma St, Englewood, CO 80110', 'Englewood, CO', '5:30 - 7:30 pm MDT', 'Join Women Who Charge for Real Women. Real EVs., a community conversation celebrating the women who are driving Colorado''s electric future. Curious about owning an EV? Wondering what charging is really like? This is your opportunity to connect with women EV owners and hear the real stories behind their electric journeys, from choosing a vehicle to road trips and lessons learned.', '5325'),
  ('2026-10-07', '', 'DGS Drive Electric Month', 'EV Showcase', '301 W. Preston St., Baltimore, MD 21201', 'Baltimore, MD', '12:00 - 2:00 pm EDT', 'Annual National Drive Electric Month event hosted by the Maryland Department of General Services.', '5393'),
  ('2026-10-08', '', 'Build an EV with PNM', 'Workshop', 'WHEELS Museum, 1100 2nd St SW, Albuquerque, NM 87102', 'Albuquerque, NM', '11:00 am - 12:00 pm MDT', 'Get ready to think like an engineer and build like an inventor. In this hands-on workshop, participants construct their own battery-powered electric vehicle while exploring the science behind electric transportation. Using a battery, motor, gears, wheels, and axles, young builders create a working electric circuit and bring a motor to life.', '5389'),
  ('2026-10-08', '', 'CEBE Energy Cafe EV Ride & Drive', 'Ride & Drive', 'Center for an Ecology-Based Economy, 447 Main Street, Norway, ME 04268', 'Norway, ME', '3:30 - 6:30 pm EDT', 'Live in western Maine and interested in EVs? Come along to CEBE''s Energy Cafe, where this gathering focuses on electric vehicles. We will have at least six different EVs to view, drive and ask questions about. As well as learning about local residents'' experience driving EVs in western Maine, we will have plenty of information on rebates, used EV purchases and general advice on going electric.', '5418'),
  ('2026-10-10', '', 'Knoxville Drive Electric Festival', 'Festival', 'Pellissippi State Community College, 10915 Hardin Valley Road, Knoxville, TN 37933', 'Knoxville, TN', '10:00 am - 3:00 pm EDT', 'The Knoxville Drive Electric Festival celebrates National Drive Electric Month at Pellissippi State Community College''s Hardin Valley campus. See the full listing on the National Drive Electric Month site for the programme, exhibitors and registration details.', '5126'),
  ('2026-10-10', '', 'Norton Commons National Drive Electric Month', 'Festival', 'Norton Commons North Village Square, Rosebay St., Louisville/Prospect, KY 40059', 'Louisville/Prospect, KY', '12:00 - 4:00 pm EDT', 'Join Evolve KY at Norton Commons for National Drive Electric Month. Experience a festival atmosphere featuring food trucks, kids'' activities, and a massive EV showcase. Whether you''re an EV owner, dealer, eco-vendor, or just curious, come out to test drive vehicles and get real answers to all your electric vehicle questions. Get behind the wheel and feel the performance yourself, and meet experienced local owners.', '5312'),
  ('2026-10-10', '', '2026 3rd Annual Albuquerque EV Expo', 'Expo', 'North Domingo Baca Park, dog park parking lot, 7520 Corona Ave NE, Albuquerque, NM 87113', 'Albuquerque, NM', '10:00 am - 3:00 pm MDT', 'Dozens of Albuquerque electric vehicle drivers and enthusiasts host this event so community members can get their questions answered about what driving and owning an electric vehicle is really like. We focus on how your electric vehicle can provide additional benefits, such as cooking on induction stovetops, keeping beverages cold while camping, and running power tools in remote locations.', '5314'),
  ('2026-10-10', '', 'Electrify Your Drive! Free EV Car Show in Old Saybrook', 'EV Showcase', 'Kathleen E. Goodwin School, 80 Old Boston Post Road, Old Saybrook, CT 06475', 'Old Saybrook, CT', '12:00 - 2:00 pm EDT', 'Join us for a National Drive Electric Month event in Old Saybrook. Learn about multiple makes and models of EVs and plug-in hybrid EVs (PHEVs) from car owners as well as local dealers. This is the eighth annual Old Saybrook NDEM event. Experienced EV and PHEV owners will display their vehicles and answer questions.', '5321'),
  ('2026-10-10', '', 'Akimatsuri Fall Festival', 'Festival', 'East San Gabriel Valley Japanese Community Center, 1203 W. Puente Ave., West Covina, CA 91790', 'West Covina, CA', '12:00 - 6:00 pm PDT', 'Join the East San Gabriel Valley Japanese Community Center for Akimatsuri Fall Festival, a vibrant celebration of Japanese culture, community and sustainability. Akimatsuri brings together families, friends and neighbours for a day of cultural experiences, entertainment, food, education and community connection, held in connection with National Drive Electric Month and in partnership with Southern California Edison.', '5360'),
  ('2026-10-10', '', 'Hoosier EVA at Bloomington Farmers'' Market', 'EV Showcase', 'Showers Commons, City Hall, 401 N Morton Street, Bloomington, IN 47404', 'Bloomington, IN', '9:00 am - 12:30 pm EDT', 'At the Bloomington Community Farmers'' Market, we welcome neighbours, families and curious visitors to stop by and learn more about the growing world of electric transportation. Our booth is hosted by the newly reformed Hoosier Electric Vehicle Association, a local group reconnecting EV owners, supporters, and anyone interested in cleaner, quieter ways to get around.', '5381'),
  ('2026-10-10', '', 'Clarksville Electric Ride and Drive', 'Ride & Drive', 'CDE Lightband, 2021 Wilma Rudolph Blvd, Clarksville, TN 37040', 'Clarksville, TN', '3:30 - 5:30 pm CDT', 'CDE Lightband hosts an electric ride and drive for National Drive Electric Month. Full programme details are still being confirmed by the organisers — check the National Drive Electric Month listing for the latest.', '5397'),
  ('2026-10-10', '', 'Fall EV Showcase at Pepper Place Market', 'EV Showcase', 'Pepper Place Market, 2930 3rd Ave S, Birmingham, AL 35233', 'Birmingham, AL', '8:00 am - 12:00 pm CDT', 'The Birmingham Area Chapter of Drive Electric Alabama hosts its Fall EV Showcase at the vibrant Pepper Place Market. This event brings together electric vehicle enthusiasts, local businesses, and community members to celebrate the benefits of electric mobility. Attendees will have the opportunity to explore a variety of electric vehicles and learn about the latest advancements in EV technology.', '5398'),
  ('2026-10-10', '', 'Appleton Drive Electric', 'EV Showcase', 'Prince of Peace Lutheran Church, 2330 E Calumet St, Appleton, WI 54815', 'Appleton, WI', '10:00 am - 3:00 pm CDT', 'Welcome to the Drive Electric Month car show for electric cars at Prince of Peace Lutheran Church on East Calumet Street in Appleton, Wisconsin. Owners, please have your car in the west parking lot by 9:30 a.m., half an hour before the event starts. Bring materials to pass out on electric cars, and if you''re interested in sharing your car and giving rides to people, please do so.', '5408'),
  ('2026-10-10', '', 'Drive Electric & Light Electric Repair Workshop', 'Workshop', 'TS Designs, 2053 Willow Springs Ln, Burlington, NC 27215', 'Burlington, NC', '10:00 am - 1:30 pm EDT', 'Come and revive your light electric vehicles — e-bikes, e-scooters, mini Segways and e-trikes — as well as share your full-size EV experiences. Our central NC regional Electric Vehicle Association chapter, TEVA of NC, is collaborating with TS Designs to put on a Light Electric Repair Workshop. Advance registration is required for any light electric setup.', '5410'),
  ('2026-10-12', '', 'Let''s Taco ''Bout EVs!', 'EV Showcase', 'O.L. Darner Field, 900 Myrtle St., Scott City, KS 67871', 'Scott City, KS', '4:30 - 6:30 pm CDT', 'Scott City, let''s taco ''bout EVs. We''re celebrating National Drive Electric Month with free tacos, Monday night football, and a chance to get up close with Wheatland Electric''s all-electric vehicles. Check out our Hyundai Kona Electric and Ford F-150 Lightning, and get answers to those EV questions you''ve always wondered about. No sales pitch, no pressure.', '5422')
) as v(event_date, end_date, title, type, location, region, time, description, eid);

-- Sanity check. Raises if the import did not land in full, or if the
-- hand-authored Poolesville row was lost, so either failure is noisy rather
-- than silent.
do $$
declare
  n_imported integer;
  n_kept     integer;
begin
  select count(*) into n_imported from public.site_events
  where register_url like 'https://driveelectricmonth.org/event?eventid=%'
    and register_url <> 'https://driveelectricmonth.org/event?eventid=5288';

  select count(*) into n_kept from public.site_events
  where register_url = 'https://driveelectricmonth.org/event?eventid=5288';

  if n_imported <> 120 then
    raise exception 'NDEM import expected 120 rows, found %', n_imported;
  end if;
  if n_kept <> 1 then
    raise exception 'The hand-authored Poolesville row (5288) should still be here exactly once, found %', n_kept;
  end if;
end $$;
