// EPA range in miles, by model year and by variant — the figure that belongs on
// a USED car, and on a particular one.
//
// src/data/ev-catalog.ts carries one range per nameplate: the current car. That
// is right for the comparison pages, which price new cars, and wrong everywhere
// a second-hand listing appears. A 2013 Nissan LEAF was showing 303 miles, the
// figure for a 2026 LEAF; it does 75.
//
// One model year is not one figure either. The EPA rates a 2026 LYRIQ four
// times — 326 rear-drive, 319 PAWD, 303 AWD, 285 V-Series — so a card that
// said "285–326 mi" was quoting a spread no car on it achieves. Every listing
// names its trim and its drivetrain, which is usually enough to pick one row.
//
// Generated by scripts/refresh-ev-ranges.py from the EPA's own vehicle dataset
// (fueleconomy.gov/feg/epadata/vehicles.csv), every battery-electric row from
// 2011 on, grouped by the car it matches in our catalog.
//
// No imports: the marketplace's serverless function reads this too.

/** One figure, or the low and high of that year's variants. */
export type EpaRangeBand = readonly [number] | readonly [number, number];

/**
 * One EPA rating: miles, drive letter, and the words that tell it apart.
 *
 * The drive letter is "r", "f", "a" or "" — four-wheel drive counts as all-wheel
 * because listings write both as AWD. The third cell is the EPA's model text
 * with the nameplate and the drive words removed ("Model 3 Long Range AWD" →
 * "long range"), and is absent when nothing distinguishes the row.
 */
export type EpaVariant = readonly [number, string] | readonly [number, string, string];

/** What a listing knows about itself, and we can match a variant against. */
export interface ListingVariantHint {
  trim?: string;
  drivetrain?: string;
}

// ── generated: EPA variants ─────────────────────────────────────────────────
export const EV_RANGE_VARIANTS: Readonly<Record<string, Readonly<Record<number, readonly EpaVariant[]>>>> = {
  "acura-zdx": {
    2024: [[278, "a", "type s"], [304, "a"], [313, "r"]],
    2026: [[296, "a", "type s"], [323, "a"], [327, "r"]],
  },
  "audi-a6-etron": {
    2027: [[327, "a"], [348, "r"], [360, "a", "ultra"], [395, "r", "ultra"]],
  },
  "audi-e-tron": {
    2019: [[204, "a"]],
    2020: [[218, "a", "sportback"]],
    2021: [[218, "a", "sportback"], [222, "a"]],
    2022: [[181, "a", "s 21 22 inch wheels"], [185, "a", "s sportback 21 22 inch wheels"], [208, "a", "s 20in wheels"], [212, "a", "s sportback 20 inch wheels"], [218, "a", "sportback"], [222, "a"]],
    2023: [[181, "a", "s 21 22 inch wheels"], [185, "a", "s sportback 21 22 inch wheels"], [208, "a", "s 20 inch wheels"], [212, "a", "s sportback 20 inch wheels"], [225, "a", "sportback"], [226, "a"]],
    2024: [[218, "a", "sq8 sportback 21 22 inch wheels"], [236, "a", "q4 50"], [242, "a", "q4 sportback 50"], [253, "a", "sq8 sportback 20 inch wheels"], [258, "a", "q4 55"], [258, "a", "q4 sportback 55"], [265, "r", "q4 40"], [296, "a", "q8 sportback"], [300, "a", "q8 sportback ultra"]],
    2025: [[208, "a", "sq8 sportback 21 22 inch wheels"], [242, "a", "sq8 sportback 20 inch wheels"], [254, "a", "q8 sportback 21 inch wheels"], [258, "a", "q4 55"], [258, "a", "q4 sportback 55"], [272, "a", "q8 sportback 20 inch wheels"], [283, "a", "sq6 sportback"], [288, "r", "q4 45"], [305, "a", "q6 sportback 20 inch wheels"], [319, "a", "q6 sportback 19 inch wheels"]],
    2026: [[251, "a", "q4 55"], [251, "a", "q4 sportback 55"], [288, "r", "q4 45"]],
    2027: [[264, "a", "sq6 sportback 21 inch tires"], [285, "a", "sq6 sportback 20 inch tires"], [311, "a", "s6 21 inch wheels"], [325, "a", "q6 sportback"], [326, "a", "s6 20 inch wheels"]],
  },
  "audi-e-tron-gt": {
    2022: [[232, "a", "rs"], [238, "a"]],
    2023: [[232, "a", "rs"], [238, "a"]],
    2024: [[249, "a"], [249, "a", "rs"]],
    2025: [[278, "a", "rs performance"], [294, "a", "s 21 inch wheels"], [300, "a", "s 20 inch wheels"]],
    2026: [[278, "a", "rs performance"], [294, "a", "s 21 inch wheels"], [300, "a", "s 20 inch wheels"]],
    2027: [[278, "a", "rs performance"], [294, "a", "s 21 inch wheels"], [300, "a", "s 20 inch wheels"]],
  },
  "audi-q4-etron": {
    2022: [[241, "a"]],
    2023: [[236, "a"], [242, "a"], [265, "r"]],
  },
  "audi-q6-etron": {
    2025: [[275, "a"], [295, "a", "20 inch wheels"], [298, "r", "20 inch wheels"], [307, "a", "19 inch wheels"], [310, "r", "19 inch wheels"], [321, "r", "ultra"]],
    2027: [[264, "a", "21 inch tires"], [285, "a", "20 inch tires"], [301, "a", "20 inch tires"], [301, "a", "sb 20 inch tires"], [325, "a", "19 inch tires"]],
  },
  "audi-q8-e-tron": {
    2024: [[218, "a", "sq8 21 22 inch wheels"], [253, "a", "sq8 20 inch wheels"], [285, "a"]],
    2025: [[208, "a", "sq8 21 22 inch wheels"], [242, "a", "sq8 20 inch wheels"], [254, "a", "21 inch wheels"], [272, "a", "20 inch wheels"]],
  },
  "bmw-i3": {
    2014: [[81, "r", "bev"]],
    2015: [[81, "r", "bev"]],
    2016: [[81, "r", "bev"]],
    2017: [[81, "r", "bev 60 amp hour battery"], [114, "r", "bev 94 amp hour battery"]],
    2018: [[107, "r", "i3s 94ah"], [114, "r", "94ah"]],
    2019: [[153, "r"], [153, "r", "i3s"]],
    2020: [[153, "r"], [153, "r", "i3s"]],
    2021: [[153, "r"], [153, "r", "i3s"]],
  },
  "bmw-i4": {
    2022: [[227, "a", "m50 gran coupe 20 inch wheels"], [270, "a", "m50 gran coupe 19 inch wheels"], [282, "r", "edrive40 gran coupe 19 inch wheels"], [301, "r", "edrive40 gran coupe 18 inch wheels"]],
    2023: [[227, "a", "m50 gran coupe 20 inch wheels"], [235, "r", "edrive35 gran coupe 19 inch wheels"], [256, "r", "edrive35 gran coupe 18 inch wheels"], [271, "a", "m50 gran coupe 19 inch wheels"], [282, "r", "edrive40 gran coupe 19 inch wheels"], [301, "r", "edrive40 gran coupe 18 inch wheels"]],
    2024: [[227, "a", "m50 gran coupe 20 inch wheels"], [252, "r", "edrive35 gran coupe 19 inch wheels"], [269, "a", "m50 gran coupe 19 inch wheels"], [276, "r", "edrive35 gran coupe 18 inch wheels"], [279, "a", "xdrive40 gran coupe 19 inch wheels"], [283, "r", "edrive40 gran coupe 19 inch wheels"], [301, "r", "edrive40 gran coupe 18 inch wheels"], [307, "a", "xdrive40 gran coupe 18 inch wheels"]],
    2025: [[227, "a", "m50 gran coupe 20 inch wheels"], [244, "r", "edrive35 gran coupe 19 inch wheels"], [266, "r", "edrive35 gran coupe 18 inch wheels"], [267, "a", "m50 gran coupe 19 inch wheels"], [268, "a", "xdrive40 gran coupe 19 inch wheels"], [287, "a", "xdrive40 gran coupe 18 inch wheels"], [295, "r", "edrive40 gran coupe 19 inch wheels"], [318, "r", "edrive40 gran coupe 18 inch wheels"]],
    2026: [[232, "a", "m60 gran coupe 20 inch wheels"], [251, "r", "edrive35 gran coupe 19 inch wheels"], [268, "a", "xdrive40 gran coupe 19 inch wheels"], [278, "a", "m60 gran coupe 19 inch wheels"], [287, "a", "xdrive40 gran coupe 18 inch wheels"], [307, "r", "edrive40 gran coupe 19 inch wheels"], [333, "r", "edrive40 gran coupe 18 inch wheels"]],
  },
  "bmw-i5": {
    2024: [[240, "a", "m60 sedan 21 inch wheels"], [248, "a", "m60 sedan 20 inch wheels"], [256, "a", "m60 sedan 19 inch wheels"], [270, "r", "edrive40 sedan 21 inch wheels"], [278, "r", "edrive40 sedan 20 inch wheels"], [295, "r", "edrive40 sedan 19 inch wheels"]],
    2025: [[239, "a", "m60 sedan 21 inch wheels"], [248, "a", "xdrive40 sedan 21 inch wheels"], [250, "a", "m60 sedan 20 inch wheels"], [253, "a", "m60 sedan 19 inch wheels"], [262, "a", "xdrive40 sedan 20 inch wheels"], [266, "a", "xdrive40 sedan 19 inch wheels"], [271, "r", "edrive40 sedan 21 inch wheels"], [278, "r", "edrive40 sedan 20 inch wheels"], [295, "r", "edrive40 sedan 19 inch wheels"]],
    2026: [[259, "a", "m60 sedan 21 inch wheels"], [259, "a", "xdrive40 sedan 21 inch wheels"], [266, "a", "m60 sedan 20 inch wheels"], [272, "a", "xdrive40 sedan 20 inch wheels"], [277, "a", "m60 sedan 19 inch wheels"], [278, "a", "xdrive40 sedan 19 inch wheels"], [278, "r", "edrive40 sedan 21 inch wheels"], [300, "r", "edrive40 sedan 20 inch wheels"], [310, "r", "edrive40 sedan 19 inch wheels"]],
    2027: [[262, "a", "xdrive40 sedan 21 inch wheels"], [273, "a", "xdrive40 sedan 20 inch wheels"], [280, "r", "edrive40 sedan 21 inch wheels"], [283, "a", "xdrive40 sedan 19 inch wheels"], [299, "r", "edrive40 sedan 20 inch wheels"], [328, "r", "edrive40 sedan 19 inch wheels"]],
  },
  "bmw-i7": {
    2023: [[296, "a", "sedan 20 inch wheels"], [308, "a", "sedan 21 inch wheels"], [318, "a", "sedan 19 inch wheels"]],
    2024: [[274, "a", "m70 sedan 20 inch wheels"], [291, "a", "m70 sedan 21 inch wheels"], [298, "a", "sedan 20 inch wheels"], [301, "r", "edrive50 sedan 20 inch wheels"], [307, "a", "sedan 21 inch wheels"], [311, "r", "edrive50 sedan 21 inch wheels"], [317, "a", "sedan 19 inch wheels"], [321, "r", "edrive50 sedan 19 inch wheels"]],
    2025: [[268, "a", "m70 sedan 20 inch wheels"], [285, "a", "m70 sedan 21 inch wheels"], [296, "a", "sedan 20 inch wheels"], [301, "r", "edrive50 sedan 20 inch wheels"], [307, "r", "edrive50 sedan 21 inch wheels"], [308, "a", "sedan 21inch wheels"], [311, "a", "sedan 19 inch wheels"], [314, "r", "edrive50 sedan 19 inch wheels"]],
    2026: [[267, "a", "m70 sedan 20 inch wheels"], [285, "a", "m70 sedan 21 inch wheels"], [296, "a", "sedan 20 inch wheels"], [301, "r", "edrive50 sedan 20 inch wheels"], [307, "r", "edrive50 sedan 21 inch wheels"], [308, "a", "sedan 21 inch wheels"], [311, "a", "sedan 19 inch wheels"], [314, "r", "edrive50 sedan 19 inch wheels"]],
    2027: [[344, "a", "sedan 20 inch all season tires"], [344, "a", "sedan 21 inch all season tires"], [348, "a", "sedan 21 inch summer tires"], [354, "a", "xdrive50 sedan 20 inch all season tires"], [354, "a", "xdrive50 sedan 21 inch all season tires"], [362, "a", "sedan 20 inch summer tires"], [364, "a", "xdrive50 sedan 21 inch summer tires"]],
  },
  "bmw-ix": {
    2022: [[305, "a", "xdrive50 21 inch wheels"], [315, "a", "xdrive50 22 inch wheels"], [324, "a", "xdrive50 20 inch wheels"]],
    2023: [[274, "a", "m60 22 inch wheels"], [288, "a", "m60 21 inch wheels"], [305, "a", "xdrive50 21 inch wheels"], [315, "a", "xdrive50 22 inch wheels"], [324, "a", "xdrive50 20 inch wheels"]],
    2024: [[217, "a", "xdrive40 20 inch wheels"], [217, "a", "xdrive40 21 inch wheels"], [217, "a", "xdrive40 22 inch wheels"], [296, "a", "m60 21 inch wheels"], [296, "a", "m60 22 inch wheels"], [307, "a", "xdrive50 20 inch wheels"], [307, "a", "xdrive50 21 inch wheels"], [307, "a", "xdrive50 22 inch wheels"]],
    2025: [[211, "a", "xdrive40 21 inch wheels"], [217, "a", "xdrive40 20 inch wheels"], [219, "a", "xdrive40 22 inch wheels"], [284, "a", "m60 21 inch wheels"], [285, "a", "m60 22 inch wheels"], [302, "a", "xdrive50 22 inch wheels"], [303, "a", "xdrive50 21 inch wheels"], [309, "a", "xdrive50 20 inch wheels"]],
    2026: [[279, "a", "xdrive45 22 inch wheels"], [283, "a", "m70 23 inch wheels"], [284, "a", "m70 22 inch wheels"], [290, "a", "xdrive45 23 inch wheels"], [297, "a", "xdrive45 21 inch wheels"], [303, "a", "m70 21 inch wheels"], [312, "a", "xdrive45 20 inch wheels"], [318, "a", "xdrive60 23 inch wheels"], [327, "a", "xdrive60 22 inch wheels"], [341, "a", "xdrive60 21 inch wheels"], [364, "a", "xdrive60 20 inch wheels"]],
  },
  "bmw-ix-xdrive40": {
    2024: [[217, "a", "20 inch wheels"], [217, "a", "21 inch wheels"], [217, "a", "22 inch wheels"]],
    2025: [[211, "a", "21 inch wheels"], [217, "a", "20 inch wheels"], [219, "a", "22 inch wheels"]],
  },
  "bmw-ix3": {
    2027: [[383, "a", "50 20 inch all season tires"], [392, "a", "50 22 inch summer tires"], [398, "a", "50 21 inch summer tires"], [399, "a", "50 21 inch all season tires"], [434, "a", "50 20 inch summer tires"]],
  },
  "cadillac-celestiq": {
    2025: [[303, "a"]],
    2026: [[303, "a"]],
  },
  "cadillac-lyriq": {
    2023: [[307, "a"], [312, "r"]],
    2024: [[307, "a"], [314, "r"]],
    2025: [[303, "a", "19 kw charger"], [319, "a", "11 kw charger"], [326, "r"]],
    2026: [[285, "a", "pawd v series 11 kw charger"], [285, "a", "pawd v series 19 kw charger"], [303, "a"], [319, "a", "pawd"], [326, "r", "11 kw charger"], [326, "r", "19 kw charger"]],
    2027: [[285, "a", "v series 11kw charger"], [285, "a", "v series 19kw charger"], [303, "a", "19kw charger"], [319, "a", "11kw charger"], [326, "r", "11kw charger"], [326, "r", "19kw charger"]],
  },
  "cadillac-optiq": {
    2026: [[250, "a", "v series 19 kw charger"], [278, "a", "v series 11 kw charger"], [303, "a", "11 kw charger"], [303, "a", "19 kw charger"], [317, "r", "11 kw charger"], [317, "r", "19 kw charger"]],
    2027: [[250, "a", "v series 19kw charger"], [278, "a", "v series 11kw charger"], [303, "a", "11kw charger"], [303, "a", "19kw charger"], [317, "r", "11kw charger"], [317, "r", "19kw charger"]],
  },
  "cadillac-vistiq": {
    2026: [[300, "a", "19 kw charger"], [305, "a", "11 kw charger"]],
    2027: [[300, "a", "19kw charger"], [305, "a", "11kw charger"]],
  },
  "chevy-blazer-ev": {
    2024: [[279, "a"], [324, "r"]],
    2025: [[283, "a"], [283, "f", "22 inch tire"], [303, "a", "ss"], [312, "f"], [334, "r"]],
    2026: [[283, "a"], [283, "f", "22 inch tire"], [302, "a", "ss"], [312, "f"]],
    2027: [[283, "a"], [283, "f", "22 inch tire"], [302, "a", "ss"], [312, "f"]],
  },
  "chevy-bolt-euv": {
    2022: [[247, "f"]],
    2023: [[247, "f"]],
  },
  "chevy-bolt-ev": {
    2017: [[238, "f", "ev"]],
    2018: [[238, "f", "ev"]],
    2019: [[238, "f", "ev"]],
    2020: [[259, "f", "ev"]],
    2021: [[259, "f", "ev"]],
    2022: [[259, "f", "ev"]],
    2023: [[259, "f", "ev"]],
    2027: [[262, "f"]],
  },
  "chevy-equinox-ev": {
    2024: [[285, "a"], [319, "f"]],
    2025: [[307, "a", "11 kw charger"], [307, "a", "19 kw charger"], [319, "f"]],
    2026: [[288, "a", "19 kw charger"], [307, "a", "11 kw charger"], [319, "f"]],
    2027: [[307, "a"]],
  },
  "chevy-silverado-ev": {
    2024: [[393, "a"], [450, "a"]],
    2025: [[282, "a", "2wt"], [390, "a", "19 kw charger"], [408, "a", "11 kw charger"], [422, "a", "5wt 11 kw charger"], [422, "a", "5wt 19 kw charger"], [492, "a", "8wt"]],
    2026: [[283, "a", "std range 11kw charger"], [286, "a", "std range wt 11kw charger"], [385, "a", "ext range 19kw charger"], [410, "a", "ext range 11kw charger"], [424, "a", "ext range wt"], [493, "a", "max range wt 19kw charger"]],
  },
  "chevy-spark-ev": {
    2014: [[82, "f"]],
    2015: [[82, "f"]],
    2016: [[82, "f"]],
  },
  "dodge-charger-daytona-ev": {
    2024: [[216, "a", "2 dr scat pack track pack"], [241, "a", "2 dr scat pack track pack a s"], [268, "a", "2 dr r t 20in goodyear"], [274, "a", "2 dr r t 18in"], [308, "a", "2 dr r t 20in nexen"]],
    2025: [[216, "a", "scat pack 325 35zr20 rear"], [241, "a", "scat pack 325 35zr20 rear a s"], [268, "a", "r t 275 40r20"], [274, "a", "r t 245 55zr18"], [279, "a", "r t 305 35zr20"], [279, "a", "scat pack 305 35zr20"], [308, "a", "r t 255 45r20"]],
    2026: [[223, "a", "scat pack 325 35zr20 rear"], [241, "a", "scat pack 325 35zr20 rear a s"], [258, "a", "r t 275 40r20"], [263, "a", "r t 245 55zr18"], [267, "a", "r t 305 35zr20"], [267, "a", "scat pack 305 35zr20"], [295, "a", "r t 255 45r20"]],
    2027: [[231, "a", "scat pack 325 35zr20 rear"], [241, "a", "scat pack 325 35zr20 rear a s"], [267, "a", "scat pack 305 35zr20"]],
  },
  "fiat-500e": {
    2013: [[87, "f"]],
    2014: [[87, "f"]],
    2015: [[87, "f"]],
    2016: [[84, "f"]],
    2017: [[84, "f"]],
    2018: [[84, "f"]],
    2019: [[84, "f"]],
    2024: [[141, "f", "all season"], [149, "f"]],
    2025: [[141, "f", "all season"], [149, "f"]],
    2026: [[141, "f", "all season"], [149, "f"]],
  },
  "fisker-ocean": {
    2023: [[360, "a", "extreme one"]],
    2024: [[194, "f", "sport 22in"], [231, "f", "sport 20in"]],
  },
  "ford-f150-lightning": {
    2022: [[230, "a"], [300, "a", "platinum"], [320, "a", "extended range"]],
    2023: [[240, "a"], [300, "a", "platinum"], [320, "a", "extended range"]],
    2024: [[240, "a"], [300, "a", "platinum"], [320, "a", "extended range"], [320, "a", "pro extended range"]],
    2025: [[240, "a", "sr"], [300, "a", "er2"], [300, "a", "platinum"], [320, "a", "er1"], [320, "a", "pro er1"]],
  },
  "ford-focus-electric": {
    2012: [[76, "f"]],
    2013: [[76, "f"]],
    2014: [[76, "f"]],
    2015: [[76, "f"]],
    2016: [[76, "f"]],
    2017: [[115, "f"]],
    2018: [[115, "f"]],
  },
  "ford-mustang-mach-e": {
    2021: [[211, "a"], [230, "r"], [260, "a", "gt performance"], [270, "a", "extended"], [270, "a", "gt"], [300, "r", "extended"], [305, "r", "california route 1"]],
    2022: [[224, "a"], [247, "r"], [260, "a", "gt performance"], [270, "a", "gt"], [277, "a", "extended"], [303, "r", "extended"], [312, "a", "cal rt 1 er"], [314, "r", "cal rt 1 er"]],
    2023: [[224, "a"], [247, "r"], [250, "r", "lfp"], [260, "a", "gt performance"], [270, "a", "gt"], [290, "a", "extended"], [310, "r", "extended"], [312, "a", "cal rt 1 er"]],
    2024: [[230, "a"], [250, "r"], [265, "a", "rally"], [280, "a", "gt"], [300, "a", "extended"], [320, "r", "extended"]],
    2025: [[240, "a"], [260, "r"], [265, "a", "rally"], [280, "a", "gt"], [300, "a", "extended"], [320, "r", "extended"]],
    2026: [[240, "a"], [255, "a", "rally"], [260, "r"], [280, "a", "gt"], [300, "a", "extended"], [320, "r", "extended"]],
  },
  "ford-mustang-mach-e-gt": {
    2021: [[260, "a", "performance"], [270, "a"]],
    2022: [[260, "a", "performance"], [270, "a"]],
    2023: [[260, "a", "performance"], [270, "a"]],
    2024: [[280, "a"]],
    2025: [[280, "a"]],
    2026: [[280, "a"]],
  },
  "genesis-g80-electrified": {
    2023: [[282, "a"]],
    2024: [[282, "a"]],
    2025: [[282, "a"]],
    2026: [[300, "a"]],
  },
  "genesis-gv60": {
    2023: [[235, "a", "performance"], [248, "a", "advance"]],
    2024: [[235, "a", "performance"], [248, "a", "advanced 20 inch wheels"], [264, "a", "advanced 19 inch wheels"], [294, "r", "standard"]],
    2025: [[235, "a", "performance"], [248, "a", "advanced 20 inch wheels"], [264, "a", "19 inch wheels"], [294, "r"]],
    2026: [[252, "a", "performance"], [267, "a", "advanced 20 inch wheels"], [282, "a", "19 inch wheels"], [306, "r"]],
    2027: [[222, "a", "magma"], [267, "a", "prestige 20 inch wheels"], [282, "a", "19 inch wheels"], [306, "r"]],
  },
  "genesis-gv70-electrified": {
    2024: [[236, "a"]],
    2025: [[236, "a"]],
    2026: [[243, "a", "20 inch wheels"], [263, "a", "19 inch wheels"]],
    2027: [[250, "a"]],
  },
  "gmc-hummer-ev": {
    2024: [[279, "a", "mt tires 2m20"], [298, "a", "mt tires"], [311, "a", "2m20"], [314, "a"]],
    2025: [[282, "a", "mt tires 2x"], [289, "a", "mt tires 3x"], [312, "a", "3x"], [318, "a", "2x"]],
  },
  "gmc-hummer-ev-suv": {
    2024: [[279, "a", "mt tires 2m20"], [298, "a", "mt tires"], [303, "a", "2m20"], [314, "a"]],
    2025: [[282, "a", "mt tires 2x"], [289, "a", "mt tires 3x"], [312, "a", "3x"], [315, "a", "2x"]],
  },
  "gmc-sierra-ev": {
    2025: [[390, "a"]],
    2026: [[283, "a", "std range 11kw charger"], [385, "a", "ext range 19kw charger"], [410, "a", "ext range 11kw charger"]],
  },
  "honda-clarity-electric": {
    2017: [[89, "f", "ev"]],
    2018: [[89, "f", "ev"]],
    2019: [[89, "f", "ev"]],
  },
  "honda-fit-ev": {
    2013: [[82, "f"]],
    2014: [[82, "f"]],
  },
  "honda-prologue": {
    2024: [[273, "a", "elite"], [281, "a", "touring"], [296, "f"]],
    2025: [[283, "a", "elite"], [294, "a", "touring"], [308, "f"]],
    2026: [[283, "a", "elite"], [294, "a", "touring"], [308, "f"]],
  },
  "hyundai-ioniq-5": {
    2022: [[220, "r", "standard range"], [256, "a", "long range"], [303, "r", "long range"]],
    2024: [[220, "r", "standard range"], [260, "a", "long range"], [303, "r", "long range"]],
    2025: [[168, "r", "robo taxi"], [221, "a", "n"], [245, "r", "standard range"], [259, "a", "xrt"], [269, "a", "20 inch wheels"], [290, "a", "19 inch wheels"], [318, "r"]],
    2026: [[168, "r", "robo taxi"], [221, "a", "n"], [245, "r", "standard range"], [259, "a", "xrt"], [269, "a", "20inch wheels"], [290, "a", "19inch wheels"], [318, "r"]],
    2027: [[245, "r", "standard range"], [259, "a", "xrt"], [269, "a", "20inch wheels"], [290, "a", "19inch wheels"], [318, "r"]],
  },
  "hyundai-ioniq-5-n": {
    2025: [[221, "a"]],
    2026: [[221, "a"]],
  },
  "hyundai-ioniq-6": {
    2023: [[240, "r", "standard range"], [270, "a", "long range 20 inch wheels"], [305, "r", "long range 20 inch wheels"], [316, "a", "long range 18 inch wheels"], [361, "r", "long range 18 inch wheels"]],
    2024: [[240, "r", "standard range"], [270, "a", "long range 20 inch wheels"], [305, "r", "long range 20 inch wheels"], [316, "a", "long range 18 inch wheels"], [361, "r", "long range 18 inch wheels"]],
    2025: [[240, "r", "standard range"], [270, "a", "20 inch wheels"], [291, "r", "20 inch wheels"], [316, "a", "18 inch wheels"], [342, "r", "18 inch wheels"]],
    2027: [[245, "a", "n"]],
  },
  "hyundai-ioniq-9": {
    2026: [[311, "a", "performance"], [320, "a"], [335, "r"]],
    2027: [[311, "a", "performance"], [320, "a"], [335, "r"]],
  },
  "hyundai-ioniq-electric": {
    2017: [[124, "f"]],
    2018: [[124, "f"]],
    2019: [[124, "f"]],
    2020: [[170, "f"]],
    2021: [[170, "f"]],
  },
  "hyundai-kona-electric": {
    2019: [[258, "f"]],
    2020: [[258, "f"]],
    2021: [[258, "f"]],
    2022: [[258, "f"]],
    2023: [[258, "f"]],
    2024: [[200, "f", "standard range"], [261, "f", "long range"]],
    2025: [[200, "f", "standard range"], [230, "f", "19 inch wheels"], [261, "f", "17 inch wheels"]],
  },
  "jaguar-i-pace": {
    2019: [[234, "a"]],
    2020: [[234, "a"]],
    2021: [[234, "a", "ev400"]],
    2023: [[217, "a", "ev400 22 inch tires"], [246, "a", "ev400 20 inch tires"]],
    2024: [[217, "a", "ev400 22 inch tires"], [246, "a", "ev400 20 inch tires"]],
  },
  "jeep-recon": {
    2026: [[222, "a", "moab"]],
  },
  "jeep-wagoneer-s": {
    2024: [[270, "a", "pirelli tire"], [303, "a", "falken tire"]],
    2025: [[262, "a", "pirelli tire"], [294, "a", "falken tire"]],
    2026: [[268, "a", "pirelli tire"], [294, "a", "falken tire"]],
  },
  "kia-ev3": {
    2027: [[221, "f", "standard range"], [280, "a", "long range"], [280, "a", "long range gt"], [321, "f", "long range"]],
  },
  "kia-ev6": {
    2022: [[232, "r", "standard range"], [274, "a", "long range"], [310, "r", "long range"]],
    2023: [[206, "a", "gt"], [232, "r", "standard range"], [252, "a", "long range 20 inch tires"], [282, "a", "long range 19 inch tires"], [310, "r", "long range"]],
    2024: [[218, "a", "gt"], [232, "r", "standard range"], [252, "a", "long range 20 inch wheels"], [282, "a", "long range 19 inch wheels"], [310, "r", "long range"]],
    2025: [[231, "a", "gt"], [237, "r", "standard range"], [270, "a", "long range 20 inch wheels"], [295, "a", "long range 19 inch wheels"], [319, "r", "long range"]],
    2026: [[231, "a", "gt"], [237, "r", "standard range"], [270, "a", "long range 20 inch wheels"], [295, "a", "long range 19 inch wheels"], [319, "r", "long range"]],
  },
  "kia-ev9": {
    2024: [[230, "r", "standard range"], [270, "a", "long range gt line"], [280, "a", "long range"], [304, "r", "long range"]],
    2025: [[230, "r", "standard range"], [270, "a", "long range gt line"], [280, "a", "long range"], [304, "r", "long range"]],
    2026: [[230, "r", "standard range"], [260, "a", "gt"], [280, "a", "long range gt line"], [283, "a", "long range"], [305, "r", "long range"]],
  },
  "kia-niro-ev": {
    2019: [[239, "f", "electric"]],
    2020: [[239, "f", "electric"]],
    2021: [[239, "f", "electric"]],
    2022: [[239, "f", "electric"]],
    2023: [[253, "f", "electric"]],
    2024: [[253, "f", "electric"]],
    2025: [[253, "f", "electric"]],
    2026: [[253, "f", "electric"]],
  },
  "kia-soul-ev": {
    2015: [[93, "f"]],
    2016: [[93, "f"]],
    2017: [[93, "f"]],
    2018: [[111, "f"]],
    2019: [[111, "f"]],
    2020: [[243, "f"]],
  },
  "lexus-es-350e": {
    2026: [[292, "f", "21 inch wheels"], [307, "f", "19 inch wheels"]],
  },
  "lexus-es-500e": {
    2026: [[272, "a", "21 inch wheels"], [276, "a", "19 inch wheels"]],
  },
  "lexus-rz-450e": {
    2023: [[196, "a", "20 inch wheels"], [220, "a", "18 inch wheels"]],
    2024: [[196, "a", "20 inch wheels"], [220, "a", "18 inch wheels"], [224, "f", "20 inch wheels"], [266, "f", "18 inch wheels"]],
    2025: [[196, "a", "20 inch wheels"], [220, "a", "18 inch wheels"], [224, "f", "20 inch wheels"], [266, "f", "18 inch wheels"]],
    2026: [[228, "a", "20 inch wheels 235 50r20 255 45r20"], [229, "a", "550e"], [257, "a", "20 inch wheels 235 50r20"], [264, "a", "18 inch wheels"], [284, "f", "350e 20 inch wheels"], [301, "f", "350e 18 inch wheels"]],
  },
  "lucid-air": {
    2022: [[451, "a", "dream p w 21 inch wheels"], [469, "a", "g touring w 21 inch wheels"], [471, "a", "dream p w 19 inch wheels"], [481, "a", "dream r w 21 inch wheels"], [516, "a", "g touring w 19 inch wheels"], [520, "a", "dream r w 19 inch wheels"]],
    2023: [[384, "a", "pure with 20 inch wheels"], [384, "a", "touring with 20 inch wheels"], [384, "a", "touring with 21 inch wheels"], [410, "a", "pure with 19 inch wheels"], [425, "a", "touring with 19 inch wheels"], [446, "a", "gt p with 21 inch wheels"], [469, "a", "g touring xr with 20 inch wheels"], [469, "a", "g touring xr with 21 inch wheels"], [516, "a", "g touring xr with 19 inch wheels"]],
    2024: [[365, "a", "touring with 21inch wheels"], [382, "a", "touring with 20 inch wheels"], [394, "r", "pure with 20 inch wheels"], [411, "a", "touring with 19 inch wheels"], [419, "r", "pure with 19 inch wheels"], [427, "a", "sapphire"], [450, "a", "g touring xr with 21 inch wheels"], [485, "a", "g touring xr with 20 inch wheels"], [516, "a", "g touring xr with19 inch wheels"]],
    2025: [[361, "a", "touring with 21 inch wheels"], [372, "r", "pure with 20 inch wheels"], [377, "a", "touring with 20 inch wheels"], [406, "a", "touring with 19 inch wheels"], [420, "r", "pure with 19 inch wheels"], [427, "a", "sapphire"], [446, "a", "g touring xr with 21 inch wheels"], [480, "a", "g touring xr with 20 inch wheels"], [512, "a", "g touring xr with 19 inch wheels"]],
    2026: [[372, "r", "pure with 20 inch wheels"], [396, "a", "touring with 20 inch wheels"], [420, "r", "pure with 19 inch wheels"], [427, "a", "sapphire"], [431, "a", "touring with 19 inch wheels"], [446, "a", "g touring xr with 21 inch wheels"], [480, "a", "g touring xr with 20 inch wheels"], [512, "a", "g touring xr with19 inch wheels"]],
  },
  "lucid-gravity": {
    2025: [[386, "a", "gt w 21f22r wheels 3r"], [386, "a", "gt w 22f23r wheels 3r"], [407, "a", "gt w 21f22r wheels 2r"], [407, "a", "gt w 22f23r wheels 2r"], [437, "a", "gt w 20f21r wheels 3r"], [450, "a", "gt w 20f21r wheels 2r"]],
    2026: [[337, "a", "touring w 20f21r wheels"], [378, "a", "dream w 21f22r wheels 3r"], [378, "a", "dream w 22f23r wheels 3r"], [386, "a", "gt w 21f22r wheels 3r"], [386, "a", "gt w 22f23r wheels 3r"], [407, "a", "gt w 21f22r wheels 2r"], [407, "a", "gt w 22f23r wheels 2r"], [420, "a", "dream w 20f21r wheels 3r"], [437, "a", "gt w 20f21r wheels 3r"], [450, "a", "gt w 20f21r wheels 2r"]],
    2027: [[337, "a", "touring w 20f21r wheels"], [386, "a", "gt w 21f22r wheels 3r"], [386, "a", "gt w 22f23r wheels 3r"], [407, "a", "gt w 21f22r wheels 2r"], [407, "a", "gt w 22f23r wheels 2r"], [437, "a", "gt w 20f21r wheels 3r"], [450, "a", "gt w 20f21r wheels 2r"]],
  },
  "maserati-granturismo-folgore": {
    2024: [[242, "a"]],
    2025: [[233, "a"]],
  },
  "maserati-grecale-folgore": {
    2025: [[206, "a", "21 inch wheels"], [245, "a", "20 inch wheels"]],
    2026: [[239, "a", "21 inch wheels"], [268, "a", "19 inch wheels"], [268, "a", "20 inch wheels"]],
  },
  "mazda-mx-30": {
    2022: [[100, "f"]],
    2023: [[100, "f"]],
  },
  "mercedes-b-class-electric": {
    2014: [[87, "f"]],
    2015: [[87, "f"]],
  },
  "mercedes-cla-ev": {
    2026: [[312, "a", "cla350 tech"], [317, "r", "cla250 plus tech"], [374, "r", "cla250 plus tech r22"]],
    2027: [[312, "a", "cla350 tech"], [317, "r", "cla250 plus tech"], [374, "r", "cla250 plus tech r22"]],
  },
  "mercedes-eqb": {
    2022: [[227, "a", "350"], [243, "a", "300"]],
    2024: [[205, "a", "300"], [207, "a", "350"], [251, "f", "250 plus"]],
    2025: [[205, "a", "300"], [207, "a", "350"], [251, "f", "250 plus"]],
  },
  "mercedes-eqe": {
    2024: [[280, "a", "350"], [298, "a", "500"], [298, "r", "350 plus"]],
    2025: [[266, "a", "500"], [267, "a", "350"], [308, "r", "350 plus"]],
    2026: [[267, "a", "320"], [308, "r", "320 plus"]],
  },
  "mercedes-eqe-suv": {
    2024: [[235, "a", "amg plus"], [265, "a", "350"], [282, "a", "500"], [307, "r", "350 plus"]],
    2025: [[230, "a", "amg plus"], [253, "a", "350"], [264, "a", "500"], [302, "r", "350 plus"]],
    2026: [[230, "a", "amg plus"], [253, "a", "320"], [302, "r", "320 plus"]],
    2027: [[302, "r", "320 plus"]],
  },
  "mercedes-eqs": {
    2022: [[340, "a", "580"], [350, "r", "450 plus"]],
    2023: [[340, "a", "450"]],
    2024: [[345, "a", "450"], [345, "a", "580"], [352, "r", "450 plus"]],
    2025: [[367, "a", "450"], [371, "a", "580"], [390, "r", "450 plus"]],
    2026: [[367, "a", "450"], [371, "a", "580"], [390, "r", "450 plus"]],
  },
  "mercedes-eqs-580": {
    2022: [[340, "a"]],
    2024: [[345, "a"]],
    2025: [[371, "a"]],
    2026: [[371, "a"]],
  },
  "mercedes-eqs-suv": {
    2023: [[285, "a", "450"], [285, "a", "580"], [305, "r", "450 plus"]],
    2024: [[280, "a", "680 maybach"], [321, "a", "680 maybach"], [330, "a", "450"], [330, "a", "580"], [339, "r", "450 plus"]],
    2025: [[302, "a", "680 maybach"], [312, "a", "450"], [317, "a", "580"], [323, "r", "450 plus"]],
    2026: [[300, "a", "680 maybach"], [312, "a", "400"], [317, "a", "550"]],
    2027: [[312, "a", "400"], [317, "a", "550"]],
  },
  "mercedes-g580-ev": {
    2025: [[239, "a"]],
    2026: [[239, "a"]],
  },
  "mini-cooper-se": {
    2020: [[110, "f", "hardtop 2 door"]],
    2021: [[110, "f", "hardtop 2 door"]],
    2022: [[114, "f", "hardtop 2 door"]],
    2023: [[114, "f", "hardtop 2 door"]],
    2024: [[114, "f", "hardtop 2 door"]],
  },
  "mini-countryman-electric": {
    2025: [[204, "a", "19 inch wheels"], [212, "a", "18 inch wheels"]],
    2026: [[204, "a", "19 inch wheels"], [212, "a", "18 inch wheels"]],
    2027: [[214, "a", "19 inch wheels"], [216, "a", "18 inch wheels"]],
  },
  "mitsubishi-i-miev": {
    2012: [[62, "r"]],
    2013: [[62, "r"]],
    2014: [[62, "r"]],
    2016: [[62, "r"]],
    2017: [[59, "r"]],
  },
  "nissan-ariya": {
    2023: [[205, "a", "engage e 4orce 63kwh"], [216, "f", "engage 63kwh"], [257, "a", "plat plus e 4orce 87kwh 20"], [267, "a", "plat plus e 4orce 87kwh 19"], [272, "a", "eng plus evo plus e 4orce 87kwh"], [289, "f", "evo plus emp plus prm 87kwh"], [304, "f", "venture plus 87kwh"]],
    2024: [[205, "a", "engage e 4orce 63kwh"], [216, "f", "engage 63kwh"], [257, "a", "platinum e 4orce 87kwh 20in wheels"], [267, "a", "platinum e 4orce 87kwh 19in wheels"], [272, "a", "engage evolve e 4orce 87kwh"], [289, "f", "evolve empower 87kwh"], [304, "f", "venture plus 87kwh"]],
    2025: [[205, "a", "e 4orce 63kwh"], [216, "f", "63kwh"], [257, "a", "platinum e 4orce 87kwh 20in wheels"], [267, "a", "platinum e 4orce 87kwh 19in wheels"], [272, "a", "engage evolve e 4orce 87kwh"], [289, "f", "evolve 87kwh"]],
    2026: [[205, "a", "e 4orce 63kwh"], [216, "f", "63kwh"], [267, "a", "platinum e 4orce 87kwh 19in wheels"], [272, "a", "e 4orce 87kwh"], [289, "f", "87kwh"]],
  },
  "nissan-leaf": {
    2011: [[73, "f"]],
    2012: [[73, "f"]],
    2013: [[75, "f"]],
    2014: [[84, "f"]],
    2015: [[84, "f"]],
    2016: [[84, "f", "24 kw hr battery pack"], [107, "f", "30 kw hr battery pack"]],
    2017: [[107, "f"]],
    2018: [[151, "f"]],
    2019: [[150, "f", "40 kw hr battery pack"], [215, "f", "sv sl 62 kw hr battery pack"], [226, "f", "62 kw hr battery pack"]],
    2020: [[149, "f", "40 kw hr battery pack"], [215, "f", "sv sl 62 kw hr battery pack"], [226, "f", "62 kw hr battery pack"]],
    2021: [[149, "f", "40 kw hr battery pack"], [215, "f", "sv sl 62 kw hr battery pack"], [226, "f", "62 kw hr battery pack"]],
    2022: [[149, "f", "40 kw hr battery pack"], [215, "f", "sv sl 62 kw hr battery pack"], [226, "f", "62 kw hr battery pack"]],
    2023: [[149, "f"], [212, "f", "sv"]],
    2024: [[149, "f"], [212, "f", "sv"]],
    2025: [[149, "f"], [212, "f", "sv"]],
    2026: [[259, "f", "75kwh 19 inch wheels"], [288, "f", "75kwh 18 inch alloy wheels"], [303, "f", "75kwh 18 inch steel wheels"]],
  },
  "polestar-2": {
    2021: [[233, "a"]],
    2022: [[249, "a", "dual motor"], [270, "f", "single motor"]],
    2023: [[247, "a", "bst edition"], [260, "a", "dual motor"], [260, "a", "dual motor perf pack"], [270, "f", "single motor"]],
    2024: [[247, "a", "dual motor performance pack"], [266, "a", "dual motor 20 inch wheels"], [276, "a", "dual motor 19 inch wheels"], [307, "r", "single motor 20 inch wheels"], [320, "r", "single motor 19 inch wheels"]],
    2025: [[254, "a", "dual motor performance pack"], [268, "a", "dual motor 20 inch wheels"], [278, "a", "dual motor 19 inch wheels"], [287, "a", "3 long range dual motor 22 inch wheels"], [300, "r", "single motor 20 inch wheels"], [310, "a", "3 long range dual motor 20 inch wheels"], [314, "r", "single motor 19 inch wheels"], [315, "a", "3 long range dual motor 21 inch wheels"], [333, "r", "3 long range single motor 22 inch wheels"], [342, "r", "3 long range single motor 20 inch wheels"], [350, "r", "3 long range single motor 21 inch wheels"]],
    2026: [[281, "a", "3 long range dual motor 22 inch wheels"], [286, "r", "3 long range single motor 20 inch wheels"], [291, "r", "3 long range single motor 21 inch wheels"], [312, "a", "3 long range dual motor 21 inch wheels"]],
  },
  "polestar-3": {
    2025: [[279, "a", "long range dual motor performance pack"]],
    2026: [[281, "a", "long range dual motor performance pack"]],
  },
  "polestar-4": {
    2025: [[272, "a", "long range dual motor"], [300, "r", "long range single motor"]],
    2026: [[255, "a", "long range dual motor performance"], [280, "a", "long range dual motor"], [310, "r", "long range single motor"]],
  },
  "porsche-macan-electric": {
    2025: [[315, "r"]],
    2026: [[309, "r"], [332, "r", "20in wheels"]],
  },
  "porsche-taycan": {
    2020: [[192, "a", "turbo s"], [201, "a", "turbo"], [203, "a", "4s perf battery plus"]],
    2021: [[199, "a", "4s perf battery"], [200, "r", "perf battery"], [201, "a", "turbo s"], [202, "a", "turbo s cross turismo"], [204, "a", "turbo cross turismo"], [212, "a", "turbo"], [215, "a", "4 cross turismo"], [215, "a", "4s cross turismo"], [225, "r", "perf battery plus"], [227, "a", "4s perf battery plus"]],
    2022: [[199, "a", "4s perf battery"], [200, "r", "perf battery"], [201, "a", "turbo s"], [202, "a", "turbo s cross turismo"], [204, "a", "turbo cross turismo"], [212, "a", "turbo"], [215, "a", "4 cross turismo"], [215, "a", "4s cross turismo"], [225, "r", "perf battery plus"], [227, "a", "4s perf battery plus"], [233, "a", "gts st"], [246, "a", "gts"]],
    2023: [[206, "a", "4s performance battery"], [208, "r", "performance battery"], [222, "a", "turbo s"], [222, "a", "turbo s cross turismo"], [230, "a", "4s cross turismo"], [233, "a", "gts sport turismo"], [233, "a", "turbo cross turismo"], [235, "a", "4 cross turismo"], [235, "a", "4s perf battery plus"], [238, "a", "turbo"], [242, "r", "perf battery plus"], [246, "a", "gts"]],
    2024: [[206, "a", "4s performance battery"], [208, "r", "performance battery"], [222, "a", "turbo s"], [222, "a", "turbo s cross turismo"], [230, "a", "4s cross turismo"], [233, "a", "gts sport turismo"], [233, "a", "turbo cross turismo"], [235, "a", "4 cross turismo"], [235, "a", "4s performance battery plus"], [238, "a", "turbo"], [242, "r", "performance battery plus"], [246, "a", "gts"]],
    2025: [[252, "a", "4s performance battery"], [261, "a", "turbo s cross turismo"], [265, "a", "turbo cross turismo"], [266, "a", "turbo s"], [269, "a", "turbo gt with weissach package"], [272, "a", "4s cross turismo"], [274, "r", "performance battery"], [276, "a", "turbo gt"], [277, "a", "4 cross turismo"], [279, "a", "gts sport turismo"], [292, "a", "turbo"], [293, "a", "gts"], [294, "a", "4 perf battery plus"], [295, "a", "4s perf battery plus"], [298, "a", "turbo s 21in aero design wheel 285 35"], [315, "a", "4s perf battery plus 19 inch wheels"], [317, "a", "turbo 21in aero design wheel 285 35"], [318, "r", "perf battery plus"]],
    2026: [[251, "a", "4 performance battery"], [252, "a", "4s performance battery"], [261, "a", "turbo s cross turismo"], [265, "a", "turbo cross turismo"], [266, "a", "turbo s"], [269, "a", "turbo gt with weissach package"], [272, "a", "4s cross turismo"], [274, "r", "performance battery"], [276, "a", "turbo gt"], [277, "a", "4 cross turismo"], [279, "a", "gts sport turismo"], [292, "a", "turbo"], [293, "a", "gts"], [294, "a", "4 perf battery plus"], [295, "a", "4s perf battery plus"], [315, "a", "4 perf battery plus 19in all season m s"], [315, "a", "4s perf battery plus 19in all season m s"]],
  },
  "rivian-r1s": {
    2022: [[316, "a"]],
    2023: [[274, "a", "20 inch all terrain"], [289, "a", "20 inch wheels"], [303, "a", "22 inch wheels"], [307, "a", "20 inch all terrain dual large"], [307, "a", "20 inch all terrain performance dual large"], [321, "a", "21 inch wheels"], [341, "a", "22 inch dual large"], [341, "a", "22 inch performance dual large"], [352, "a", "21 inch dual large"], [352, "a", "21 inch performance dual large"]],
    2024: [[255, "a", "dual standard 22in"], [270, "a", "dual standard 21in"], [274, "a", "all terrain quad large 20 inch"], [277, "a", "all terrain dual standard plus 20in"], [277, "a", "at performance dual standard plus 20in"], [289, "a", "quad large 20in"], [300, "a", "dual standard plus 22in"], [300, "a", "performance dual standard 22in"], [303, "a", "quad large 22in"], [307, "a", "all terrain dual large 20in"], [307, "a", "all terrain performance dual large 20in"], [315, "a", "dual standard plus 21in"], [315, "a", "performance dual standard plus 21in"], [321, "a", "quad large 21in"], [341, "a", "dual large 22in"], [341, "a", "performance dual large 22in"], [352, "a", "dual large 21in"], [352, "a", "performance dual large 21in"], [355, "a", "all terrain dual max 20in"], [355, "a", "all terrain performance dual max 20in"], [380, "a", "dual max 22in"], [380, "a", "performance dual max 22in"], [400, "a", "dual max 21in"], [400, "a", "performance dual max 21in"]],
    2025: [[258, "a", "dual standard 20in"], [270, "a", "dual standard 22in"], [289, "a", "all terrain dual large 20in"], [289, "a", "all terrain performance dual large 20in"], [292, "a", "all terrain dual large plus 20in"], [292, "a", "all terrain performance dual large plus 20in"], [300, "a", "dual large 20in"], [300, "a", "performance dual large 20in"], [317, "a", "dual large plus 20in"], [317, "a", "performance dual large plus 20in"], [329, "a", "all terrain tri max 20in"], [329, "a", "dual large 22in"], [329, "a", "performance dual large 22in"], [330, "a", "dual large plus 22in"], [330, "a", "performance dual large plus 22in"], [370, "a", "all terrain dual max 20in"], [370, "a", "all terrain performance dual max 20in"], [371, "a", "tri max 22in"], [380, "a", "dual max 20in"], [380, "a", "performance dual max 20in"], [410, "a", "dual max 22in"], [410, "a", "performance dual max 22in"]],
    2026: [[258, "a", "dual standard 20in"], [270, "a", "dual standard 22in"], [289, "a", "all terrain dual large 20in"], [289, "a", "all terrain performance dual large 20in"], [292, "a", "all terrain dual large plus 20in"], [292, "a", "all terrain performance dual large plus 20in"], [300, "a", "dual large 20in"], [300, "a", "performance dual large 20in"], [317, "a", "dual large plus 20in"], [317, "a", "performance dual large plus 20in"], [325, "a", "quad max 20in at"], [329, "a", "all terrain tri max 20in"], [329, "a", "dual large 22in"], [329, "a", "performance dual large 22in"], [330, "a", "dual large plus 22in"], [330, "a", "performance dual large plus 22in"], [338, "a", "quad max 22in uhp"], [370, "a", "all terrain dual max 20in"], [370, "a", "all terrain performance dual max 20in"], [371, "a", "tri max 22in"], [374, "a", "quad max 22in"], [380, "a", "dual max 20in"], [380, "a", "performance dual max 20in"], [410, "a", "dual max 22in"], [410, "a", "performance dual max 22in"]],
    2027: [[289, "a", "premium 20in at"], [300, "a", "premium 20in"], [325, "a", "quad 20in at"], [329, "a", "performance 20in at"], [329, "a", "premium 22in"], [338, "a", "quad 22in uhp"], [348, "a", "performance 20in"], [370, "a", "premium long range 20in at"], [371, "a", "performance 22in"], [374, "a", "quad 22in"], [380, "a", "premium long range 20in"], [410, "a", "premium long range 22in"]],
  },
  "rivian-r1t": {
    2022: [[314, "a"]],
    2023: [[289, "a", "20 inch wheels"], [303, "a", "22 inch wheels"], [328, "a", "21 inch wheels"], [341, "a", "22 inch dual large"], [341, "a", "22 inch performance dual large"], [352, "a", "21 inch dual large"], [352, "a", "21 inch performance dual large"]],
    2024: [[255, "a", "dual standard 22in"], [270, "a", "dual standard 21in"], [274, "a", "all terrain quad large 20in"], [277, "a", "all terrain dual standard plus 20in"], [277, "a", "at performance dual standard plus 20in"], [289, "a", "quad large 20in"], [300, "a", "dual standard plus 22in"], [300, "a", "performance dual standard plus 22in"], [303, "a", "quad large 22in"], [307, "a", "all terrain dual large 20in"], [307, "a", "all terrain performance dual large 20in"], [315, "a", "dual standard plus 21in"], [315, "a", "performance dual standard plus 21in"], [328, "a", "quad large 21in"], [341, "a", "dual large 22in"], [341, "a", "performance dual large 22in"], [352, "a", "dual large 21in"], [352, "a", "performance dual large 21in"], [355, "a", "all terrain dual max 20in"], [355, "a", "all terrain performance dual max 20in"], [380, "a", "dual max 22in"], [380, "a", "performance dual max 22in"], [410, "a", "dual max 21in"], [410, "a", "performance dual max 21in"]],
    2025: [[258, "a", "dual standard 20in"], [270, "a", "dual standard 22in"], [289, "a", "all terrain dual large 20in"], [289, "a", "all terrain performance dual large 20in"], [292, "a", "all terrain dual large plus 20in"], [292, "a", "all terrain performance dual large plus 20in"], [300, "a", "dual large 20in"], [300, "a", "performance dual large 20in"], [317, "a", "dual large plus 20in"], [317, "a", "performance dual large plus 20in"], [329, "a", "all terrain tri max 20in"], [329, "a", "dual large 22in"], [329, "a", "performance dual large 22in"], [330, "a", "dual large plus 22in"], [330, "a", "performance dual large plus 22in"], [370, "a", "all terrain dual max 20in"], [370, "a", "all terrain performance dual max 20in"], [371, "a", "tri max 22in"], [380, "a", "dual max 20in"], [380, "a", "performance dual max 20in"], [420, "a", "dual max 22in"], [420, "a", "performance dual max 22in"]],
    2026: [[258, "a", "dual standard 20in"], [270, "a", "dual standard 22in"], [289, "a", "all terrain dual large 20in"], [289, "a", "all terrain performance dual large 20in"], [292, "a", "all terrain dual large plus 20in"], [292, "a", "all terrain performance dual large plus 20in"], [300, "a", "dual large 20in"], [300, "a", "performance dual large 20in"], [317, "a", "dual large plus 20in"], [317, "a", "performance dual large plus 20in"], [325, "a", "quad max 20in at"], [329, "a", "all terrain tri max 20in"], [329, "a", "dual large 22in"], [329, "a", "performance dual large 22in"], [330, "a", "dual large plus 22in"], [330, "a", "performance dual large plus 22in"], [338, "a", "quad max 22in uhp"], [370, "a", "all terrain dual max 20in"], [370, "a", "all terrain performance dual max 20in"], [371, "a", "tri max 22in"], [374, "a", "quad max 22in"], [380, "a", "dual max 20in"], [380, "a", "performance dual max 20in"], [420, "a", "dual max 22in"], [420, "a", "performance dual max 22in"]],
    2027: [[289, "a", "premium 20in at"], [300, "a", "premium 20in"], [325, "a", "quad 20in at"], [329, "a", "performance 20in at"], [329, "a", "premium 22in"], [338, "a", "quad 22in uhp"], [348, "a", "performance 20in"], [370, "a", "premium long range 20in at"], [371, "a", "performance 22in"], [374, "a", "quad 22in"], [380, "a", "premium long range 20in"], [420, "a", "premium long range 22in"]],
  },
  "rivian-r2": {
    2027: [[307, "a", "performance 20in at"], [330, "a", "performance 21in"]],
  },
  "rolls-royce-spectre": {
    2024: [[264, "a", "black badge 23 inch wheels"], [266, "a", "23 inch wheels"], [280, "a", "black badge 22 inch wheels"], [291, "a", "22 inch wheels"]],
    2025: [[251, "a", "black badge 23 inch wheels"], [253, "a", "23 inch wheels"], [266, "a", "black badge 22 inch wheels"], [277, "a", "22 inch wheels"]],
    2026: [[251, "a", "black badge 23 inch wheels"], [253, "a", "23 inch wheels"], [266, "a", "black badge 22 inch wheels"], [277, "a", "22 inch wheels"]],
  },
  "smart-fortwo-electric": {
    2011: [[63, "r", "cabriolet"], [63, "r", "coupe"]],
    2013: [[68, "r", "convertible"], [68, "r", "coupe"]],
    2014: [[68, "r", "convertible"], [68, "r", "coupe"]],
    2015: [[68, "r", "convertible"], [68, "r", "coupe"]],
    2016: [[68, "r", "convertible"], [68, "r", "coupe"]],
    2017: [[57, "r", "convertible"], [58, "r", "coupe"]],
    2018: [[57, "r", "convertible"], [58, "r", "coupe"]],
    2019: [[57, "r", "convertible"], [58, "r", "coupe"]],
  },
  "subaru-solterra": {
    2023: [[222, "a", "limited touring"], [228, "a"]],
    2024: [[222, "a", "limited touring"], [227, "a"]],
    2025: [[222, "a", "limited touring"], [227, "a"]],
    2026: [[278, "a", "20"], [288, "a"]],
    2027: [[278, "a", "20"], [288, "a"]],
  },
  "subaru-trailseeker": {
    2026: [[274, "a", "20 inch"], [281, "a"]],
    2027: [[274, "a", "20 inch"], [281, "a"]],
  },
  "subaru-uncharted": {
    2026: [[273, "a", "20 inch"], [287, "a"], [308, "f"]],
    2027: [[273, "a", "20 inch"], [287, "a"], [308, "f"]],
  },
  "tesla-cybertruck": {
    2025: [[325, "a"], [335, "r", "long range"], [335, "r", "long range 20in cyber wheels"]],
    2026: [[325, "a"], [325, "a", "dual motor"], [335, "r", "long range 20in cyber wheels"]],
  },
  "tesla-model-3": {
    2017: [[310, "r", "long range"]],
    2018: [[260, "r", "mid range"], [310, "a", "long range"], [310, "a", "long range performance"], [310, "r", "long range"]],
    2019: [[220, "r", "standard range"], [240, "r", "standard range plus"], [264, "r", "mid range"], [310, "a", "long range"], [310, "a", "long range performance"], [310, "r", "long range"]],
    2020: [[220, "r", "standard range"], [250, "r", "standard range plus"], [264, "r", "mid range"], [299, "a", "long range performance 20in"], [304, "a", "long range performance 19in"], [322, "a", "long range"], [322, "a", "long range performance 18in"], [330, "r", "long range"]],
    2021: [[263, "r", "standard range plus"], [315, "a", "performance"], [353, "a", "long range"]],
    2022: [[272, "r"], [315, "a", "performance"], [358, "a", "long range"]],
    2023: [[272, "r"], [315, "a", "performance"], [358, "a", "long range"]],
    2024: [[272, "r"], [303, "a", "performance"], [341, "a", "long range e"], [342, "a", "long range"], [363, "r", "long range"]],
    2025: [[298, "a", "performance"], [346, "a", "long range"], [346, "r", "long range i 19in wheels"], [363, "r", "long range"]],
    2026: [[309, "a", "performance"], [314, "a", "performance"], [321, "r", "standard"], [346, "a", "premium"], [363, "r", "premium"]],
  },
  "tesla-model-3-performance": {
    2021: [[315, "a"]],
    2022: [[315, "a"]],
    2023: [[315, "a"]],
    2024: [[303, "a"]],
    2025: [[298, "a"]],
    2026: [[309, "a"], [314, "a"]],
  },
  "tesla-model-s": {
    2012: [[265, "r"]],
    2013: [[139, "r", "40 kw hr battery pack"], [208, "r", "60 kw hr battery pack"], [265, "r", "85 kw hr battery pack"]],
    2014: [[208, "r", "60 kw hr battery pack"], [242, "a", "85 kw hr battery pack"], [265, "r", "85 kw hr battery pack"]],
    2015: [[208, "r", "60 kw hr battery pack"], [240, "a", "70d"], [253, "a", "p85d"], [253, "a", "p90d"], [265, "r", "85 kw hr battery pack"], [265, "r", "90 kw hr battery pack"], [270, "a", "85d"], [270, "a", "90d"]],
    2016: [[210, "r", "60 kw hr battery pack"], [218, "a", "60d"], [234, "r", "70 kw hr battery pack"], [240, "a", "70d"], [249, "r", "75 kw hr battery pack"], [253, "a", "p85d"], [259, "a", "75d"], [265, "r", "85 kw hr battery pack"], [265, "r", "90 kw hr battery pack"], [270, "a", "85d"], [270, "a", "p90d"], [294, "a", "90d"], [315, "a", "p100d"]],
    2017: [[210, "r", "60 kw hr battery pack"], [218, "a", "60d"], [249, "r", "75 kw hr battery pack"], [259, "a", "75d"], [270, "a", "p90d"], [294, "a", "90d"], [315, "a", "p100d"], [335, "a", "100d"]],
    2018: [[249, "r", "75kwh"], [259, "a", "75d"], [315, "a", "p100d"], [335, "a", "100d"]],
    2019: [[259, "a", "75d"], [285, "a", "standard range"], [315, "a", "p100d"], [325, "a", "performance 21in wheels"], [335, "a", "100d"], [345, "a", "performance 19in wheels"], [370, "a", "long range"]],
    2020: [[287, "a", "standard range"], [326, "a", "performance 21in wheels"], [348, "a", "performance 19in wheels"], [373, "a", "long range"], [402, "a", "long range plus"]],
    2021: [[334, "a", "performance 21in wheels"], [348, "a", "plaid 21inch wheels"], [387, "a", "performance 19in wheels"], [405, "a", "long range"]],
    2022: [[348, "a", "plaid 21 inch wheels"], [396, "a", "plaid 19 inch wheels"], [405, "a"]],
    2023: [[405, "a"]],
    2024: [[320, "a", "plaid 21in wheels"], [359, "a", "plaid 19in wheels"], [402, "a"]],
    2025: [[312, "a", "plaid 21in wheels"], [348, "a", "plaid 19in wheels"], [410, "a"]],
    2026: [[309, "a", "plaid 21in wheels"], [368, "a", "plaid"], [410, "a"]],
  },
  "tesla-model-x": {
    2016: [[200, "a", "60d"], [238, "a", "75d"], [250, "a", "p90d"], [257, "a", "90d"], [289, "a", "p100d"]],
    2017: [[200, "a", "60d"], [238, "a", "75d"], [250, "a", "p90d"], [257, "a", "90d"], [289, "a", "p100d"], [295, "a", "100d"]],
    2018: [[238, "a", "75d"], [289, "a", "p100d"], [295, "a", "100d"]],
    2019: [[238, "a", "75d"], [270, "a", "performance 22in wheels"], [289, "a", "p100d"], [295, "a", "100d"], [325, "a", "long range"]],
    2020: [[258, "a", "standard range"], [272, "a", "performance 22in wheels"], [305, "a", "performance 20in wheels"], [328, "a", "long range"], [351, "a", "long range plus"]],
    2021: [[300, "a", "performance 22in wheels"], [341, "a", "performance 20in wheels"], [371, "a", "long range plus"]],
    2022: [[311, "a", "plaid 22 inch wheels"], [333, "a", "plaid 20 inch wheels"], [348, "a"]],
    2023: [[311, "a", "plaid 22 inch wheels"], [333, "a", "plaid 20 inch wheels"], [348, "a"]],
    2024: [[300, "a", "plaid 22in wheels"], [326, "a", "plaid 20in wheels"], [335, "a"]],
    2025: [[294, "a", "plaid 22in wheels"], [314, "a", "plaid 20in wheels"], [329, "a"]],
    2026: [[335, "a", "plaid"], [352, "a"]],
  },
  "tesla-model-y": {
    2020: [[291, "a", "performance 21in wheels"], [315, "a", "performance"], [316, "a", "long range"]],
    2021: [[244, "r", "standard range"], [303, "a", "performance"], [326, "a", "long range"]],
    2022: [[244, "r"], [279, "a"], [303, "a", "performance"], [330, "a", "long range"]],
    2023: [[279, "a"], [303, "a", "performance"], [330, "a", "long range"]],
    2024: [[260, "r"], [279, "a", "performance"], [308, "a", "long range i"], [310, "a", "long range"], [320, "r", "long range"]],
    2025: [[277, "a", "performance"], [311, "a", "long range"], [337, "r", "long range"]],
    2026: [[294, "a", "standard"], [303, "r", "standard 19in wheels"], [306, "a", "performance"], [321, "r", "standard 18in wheels"], [327, "a", "long range"], [357, "r", "long range"]],
  },
  "toyota-bz4x": {
    2023: [[222, "a", "bz4x limited"], [228, "a", "bz4x"], [242, "f", "bz4x limited"], [252, "f", "bz4x"]],
    2024: [[222, "a", "bz4x limited"], [228, "a", "bz4x"], [236, "f", "bz4x limited"], [252, "f", "bz4x"]],
    2025: [[222, "a", "bz4x 20inch wheels"], [222, "a", "bz4x limited"], [228, "a", "bz4x 18inch wheels"], [236, "f", "bz4x limited"], [252, "f", "bz4x"]],
    2026: [[236, "f", "energy capacity 200 ah"], [260, "a", "woodland 235 65r18"], [278, "a", "limited"], [281, "a", "woodland 235 60r18"], [288, "a"], [296, "f", "limited energy capacity 200 ah"], [299, "f", "limited energy capacity 191 ah"], [314, "f", "energy capacity 191 ah"]],
  },
  "toyota-chr-ev": {
    2026: [[273, "a", "20inch"], [287, "a", "18inch"]],
  },
  "toyota-rav4-ev": {
    2012: [[103, "f"]],
    2013: [[103, "f"]],
    2014: [[103, "f"]],
  },
  "vinfast-vf8": {
    2023: [[191, "a", "plus"], [207, "a", "eco"]],
    2025: [[235, "a", "plus"], [256, "a", "eco"]],
    2027: [[235, "a", "plus"], [256, "a", "eco"]],
  },
  "vinfast-vf9": {
    2024: [[291, "a", "plus"], [330, "a", "eco"]],
    2025: [[287, "a", "plus"]],
    2027: [[287, "a", "plus"]],
  },
  "volvo-c40": {
    2021: [[208, "a", "xc40 bev"]],
    2022: [[226, "a", "twin"]],
    2023: [[226, "a", "twin"]],
    2024: [[257, "a", "twin"], [297, "r"]],
    2025: [[268, "a", "twin"], [298, "r"]],
    2026: [[268, "a", "twin"], [298, "r"]],
  },
  "volvo-ex30": {
    2025: [[250, "a", "twin performance 20 inch wheels"], [253, "a", "twin performance 19 inch wheels"], [257, "r", "single motor extended range 18 inch wheels"], [261, "r", "single motor extended range 19 20 inch wheels"]],
    2026: [[203, "a", "cross country 18 inch wheels"], [227, "a", "cross country 19 inch wheels"], [253, "a", "twin performance"], [261, "r", "single motor extended range"]],
  },
  "volvo-ex40": {
    2022: [[223, "a", "twin"]],
    2023: [[223, "a", "twin"]],
    2024: [[254, "a", "twin"], [293, "r"]],
    2025: [[260, "a", "twin"], [296, "r"]],
    2026: [[260, "a", "twin"], [296, "r"]],
  },
  "volvo-ex90": {
    2025: [[300, "a", "twin motor 20 and 22 inch wheels"], [300, "a", "twin motor performance 20 and 22 inch wheels"], [310, "a", "twin motor 21 inch wheels"], [310, "a", "twin motor performance 21 inch wheels"]],
    2026: [[276, "r"], [291, "r", "21 inch wheels"], [298, "a", "twin motor"], [298, "a", "twin motor performance"], [305, "a", "twin motor 21 inch wheels"], [305, "a", "twin motor performance 21 inch wheels"]],
    2027: [[276, "r"], [300, "a", "twin motor"], [300, "a", "twin motor performance"], [310, "a", "twin motor 21 inch wheels"], [310, "a", "twin motor performance 21 inch wheels"]],
  },
  "vw-e-golf": {
    2015: [[83, "f"]],
    2016: [[83, "f"]],
    2017: [[125, "f"]],
    2018: [[125, "f"]],
    2019: [[125, "f"]],
  },
  "vw-id-buzz": {
    2025: [[231, "a", "4motion"], [234, "r"]],
  },
  "vw-id4": {
    2021: [[240, "a", "pro s"], [249, "a", "pro"], [250, "r", "1st"], [250, "r", "pro s"], [260, "r", "pro"]],
    2022: [[245, "a", "pro s"], [251, "a", "pro"], [262, "r", "pro s"], [275, "r", "pro"]],
    2023: [[209, "r"], [209, "r", "s"], [255, "a", "pro"], [255, "a", "pro s"], [275, "r", "pro"], [275, "r", "pro s"]],
    2024: [[206, "r"], [206, "r", "s"], [263, "a", "pro"], [263, "a", "pro s"], [291, "r", "pro"], [291, "r", "pro s"]],
    2025: [[206, "r"], [206, "r", "s"], [263, "a", "pro"], [263, "a", "pro s"], [291, "r", "pro"], [291, "r", "pro s"]],
    2026: [[263, "a"], [291, "r"]],
  },
};
// ── end generated ───────────────────────────────────────────────────────────

/** Low and high of a set of variants. */
const bandOf = (variants: readonly EpaVariant[]): EpaRangeBand | undefined => {
  if (!variants.length) return undefined;
  const miles = variants.map((v) => v[0]);
  const lo = Math.min(...miles);
  const hi = Math.max(...miles);
  return lo === hi ? [lo] : [lo, hi];
};

/**
 * Every variant of a car in a year, collapsed to one band.
 *
 * Kept for the callers that have no listing to narrow by, and for the tests
 * that pin the dataset itself.
 */
export const EV_RANGE_BY_YEAR: Readonly<Record<string, Readonly<Record<number, EpaRangeBand>>>> =
  Object.fromEntries(
    Object.entries(EV_RANGE_VARIANTS).map(([id, byYear]) => [
      id,
      Object.fromEntries(
        Object.entries(byYear)
          .map(([year, variants]) => [Number(year), bandOf(variants)])
          .filter(([, band]) => band != null),
      ),
    ]),
  );

/** How far a model year may be from one we hold before the figure stops being
 *  evidence about that car: a facelift moves range, a decade moves it entirely. */
const NEAREST_YEAR_TOLERANCE = 2;

/** Drivetrain words, however a dealer writes them, as the EPA's drive letter. */
const DRIVE_LETTERS: Readonly<Record<string, string>> = {
  rwd: "r", rear: "r",
  fwd: "f", front: "f",
  awd: "a", all: "a", "4wd": "a", "4x4": "a", "4matic": "a", quattro: "a", xdrive: "a",
};

/** Words that appear in trims without saying which car it is. */
const NOISE = new Set([
  "4dr", "2dr", "suv", "sedan", "coupe", "hatchback", "wagon", "crossover", "truck",
  "electric", "ev", "bev", "base", "w", "pkg", "package", "with", "and", "the",
  "rwd", "fwd", "awd", "4wd", "4x4", "2wd", "4matic", "quattro", "xdrive",
]);

/**
 * Words in an EPA label that describe EQUIPMENT rather than which trim the car
 * is: the battery, the wheels, the on-board charger.
 *
 * The distinction decides what a vague trim is allowed to mean. A dealer will
 * happily leave "extended range" or "20-inch wheels" out of the trim field, so
 * those ratings have to stay in the band; a dealer does not leave out
 * "V-Series", so a listing that does not claim one is not one.
 *
 * A label made only of these words — or of nothing — is the ordinary car.
 */
const EQUIPMENT_WORDS = new Set([
  "kw", "kwh", "charger", "inch", "in", "wheel", "wheels", "alloy", "steel",
  "battery", "pack", "range", "extended", "standard", "long", "short",
  "er", "sr", "lr", "lfp", "nmc", "dual", "single", "motor", "tires",
]);

/** Whether this variant is the plain car rather than a named trim. */
const isPlainVariant = (variant: EpaVariant): boolean =>
  words(variant[2]).every((w) => EQUIPMENT_WORDS.has(w) || /^\d+$/.test(w));

const words = (text?: string): string[] =>
  (text ?? "").toLowerCase().match(/[a-z0-9]+/g) ?? [];

const driveOf = (text?: string): string | undefined => {
  for (const word of words(text)) {
    const letter = DRIVE_LETTERS[word];
    if (letter) return letter;
  }
  return undefined;
};

/**
 * The variants a listing could be, narrowed as far as its own words allow.
 *
 * Drivetrain first, because it is the one field dealers fill in reliably, then
 * trim words. A filter that would leave nothing is not applied: a car we cannot
 * place among the variants is still a car of that year, so it keeps the year's
 * whole band rather than losing its range entirely.
 */
function narrow(variants: readonly EpaVariant[], hint?: ListingVariantHint): readonly EpaVariant[] {
  let kept = variants;

  const drive = driveOf(hint?.drivetrain);
  if (drive) {
    const byDrive = kept.filter((v) => v[1] === drive);
    if (byDrive.length) kept = byDrive;
  }

  const spoken = words(hint?.trim).filter((w) => !NOISE.has(w));
  const wanted = spoken.filter((w, i) => (
    // A one-letter word only counts when it is the whole trim. Hyundai sells
    // both an IONIQ 5 N (221 miles) and an IONIQ 5 SEL with the N Line package
    // (290), and matching on that lone "n" handed the SEL the N's rating.
    (w.length > 1 || spoken.length === 1)
    // "GT-Line", "N Line" and "Sport Package" are decor sold on the ordinary
    // car and named after the fast one, so the word before "line" or "package"
    // is not a claim to be it. A Kia EV9 GT-Line does 280 miles; the GT, 260.
    && spoken[i + 1] !== "line" && spoken[i + 1] !== "package"
  ));
  if (wanted.length) {
    const scored = kept.map((v) => {
      const have = words(v[2]);
      const hit = new Set(have.filter((w) => wanted.includes(w)));
      // Ties break towards the label with least left over, so a car that says
      // "GT" takes the EV9 GT rather than the GT-Line, whose label also
      // contains "gt" but three words we were told nothing about.
      return { v, score: hit.size, spare: have.length - hit.size };
    });
    const best = Math.max(...scored.map((s) => s.score));
    if (best > 0) {
      const tightest = Math.min(...scored.filter((s) => s.score === best).map((s) => s.spare));
      return scored.filter((s) => s.score === best && s.spare === tightest).map((s) => s.v);
    }

    // Nothing matched, so this car is none of the named trims: a LYRIQ Luxury
    // is not the V-Series whose 285 miles was setting the low end.
    //
    // Only where an ordinary car exists to fall back to, though. Every BMW iX
    // the EPA rates carries a trim word — xDrive40, xDrive50, M60 — so dropping
    // the named ones once left the xDrive50 alone and quoted a 217-mile
    // xDrive40 at 307. When every variant is a named trim, the trim text told
    // us nothing and the year's whole band is the honest answer.
    const plain = kept.filter(isPlainVariant);
    if (plain.length) kept = plain;
  }

  return kept;
}

/**
 * EPA range for one car in one model year, for this listing where we can tell.
 *
 * Returns nothing when we hold no figure close enough to the year asked for —
 * the caller then shows no range at all, which is the honest answer. Showing
 * the current car's range on a ten-year-old listing is not.
 */
export function epaRangeFor(
  catalogId: string, year?: number, hint?: ListingVariantHint,
): { rangeMi?: number; rangeMaxMi?: number } {
  const byYear = EV_RANGE_VARIANTS[catalogId];
  if (!byYear || !year) return {};

  const exact = byYear[year];
  const variants = exact ?? (() => {
    let best: readonly EpaVariant[] | undefined;
    let bestGap = Infinity;
    for (const [candidate, value] of Object.entries(byYear)) {
      const gap = Math.abs(Number(candidate) - year);
      if (gap < bestGap && gap <= NEAREST_YEAR_TOLERANCE) { best = value; bestGap = gap; }
    }
    return best;
  })();

  if (!variants?.length) return {};
  const band = bandOf(narrow(variants, hint));
  if (!band) return {};
  return band.length === 1
    ? { rangeMi: band[0] }
    : { rangeMi: band[0], rangeMaxMi: band[1] };
}
